/* Generated by re2c 0.13.5 on Wed Aug  1 18:33:13 2012 */
#line 1 "/home/weyrick/workspace/efind/src/scanner.re"
/*

Copyright (c) 2012, Shannon Weyrick <weyrick@mozek.us>
All rights reserved.

Redistribution and use in source and binary forms, with or without
modification, are permitted provided that the following conditions are met:
    * Redistributions of source code must retain the above copyright
      notice, this list of conditions and the following disclaimer.
    * Redistributions in binary form must reproduce the above copyright
      notice, this list of conditions and the following disclaimer in the
      documentation and/or other materials provided with the distribution.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
DISCLAIMED. IN NO EVENT SHALL <COPYRIGHT HOLDER> BE LIABLE FOR ANY
DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
(INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
(INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

*/

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#define _IN_SCANNER
#include "scanner.h"
#if 0
#define DEBUG(stmt) stmt
#else
#define DEBUG(stmt)
#endif

int scan(scanner_state *s, scanner_token *token) {

	int r=SCANNER_RETCODE_IMPOSSIBLE;
    char *q=s->start; //keep initial start

#define YYCTYPE char
#define YYCURSOR (s->start)
#define YYLIMIT (s->end)
#define YYMARKER (s->ptr)
#define YYDEBUG(s, c) printf("state: %d char: %c\n", s, c)

	while(SCANNER_RETCODE_IMPOSSIBLE == r) {
	
		
#line 55 "/home/weyrick/workspace/efind/src/scanner.c"
		{
			YYCTYPE yych;

			yych = *YYCURSOR;
			switch (yych) {
			case 0x00:	goto yy25;
			case '\t':
			case '\n':
			case '\r':
			case ' ':	goto yy20;
			case '*':
			case '-':
			case '.':
			case '/':
			case '?':
			case 'C':
			case 'H':
			case 'J':
			case 'Q':
			case 'T':
			case 'V':
			case 'X':
			case 'Y':
			case 'Z':
			case '_':
			case 'c':
			case 'h':
			case 'j':
			case 'q':
			case 't':
			case 'v':
			case 'x':
			case 'y':
			case 'z':	goto yy24;
			case '0':
			case '1':
			case '2':
			case '3':
			case '4':
			case '5':
			case '6':
			case '7':
			case '8':
			case '9':	goto yy22;
			case 'A':
			case 'a':	goto yy4;
			case 'B':
			case 'b':	goto yy9;
			case 'D':
			case 'd':	goto yy14;
			case 'E':
			case 'e':	goto yy18;
			case 'F':
			case 'f':	goto yy16;
			case 'G':
			case 'g':	goto yy8;
			case 'I':
			case 'i':	goto yy12;
			case 'K':
			case 'k':	goto yy10;
			case 'L':
			case 'l':	goto yy17;
			case 'M':
			case 'm':	goto yy11;
			case 'N':
			case 'n':	goto yy5;
			case 'O':
			case 'o':	goto yy2;
			case 'P':
			case 'p':	goto yy15;
			case 'R':
			case 'r':	goto yy19;
			case 'S':
			case 's':	goto yy6;
			case 'U':
			case 'u':	goto yy7;
			case 'W':
			case 'w':	goto yy13;
			default:	goto yy27;
			}
yy2:
			++YYCURSOR;
			switch ((yych = *YYCURSOR)) {
			case 'R':
			case 'r':	goto yy208;
			case 'W':
			case 'w':	goto yy210;
			default:	goto yy30;
			}
yy3:
#line 225 "/home/weyrick/workspace/efind/src/scanner.re"
			{
                    token->tokType = TOKEN_WORD;
                    token->data = strndup(q, YYCURSOR - q);
                    return 0;
                }
#line 152 "/home/weyrick/workspace/efind/src/scanner.c"
yy4:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'N':
			case 'n':	goto yy205;
			default:	goto yy30;
			}
yy5:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'A':
			case 'a':	goto yy175;
			case 'O':
			case 'o':	goto yy176;
			default:	goto yy30;
			}
yy6:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'I':
			case 'i':	goto yy165;
			case 'O':
			case 'o':	goto yy166;
			default:	goto yy30;
			}
yy7:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'I':
			case 'i':	goto yy162;
			default:	goto yy30;
			}
yy8:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'B':
			case 'b':	goto yy139;
			case 'I':
			case 'i':	goto yy141;
			case 'R':
			case 'r':	goto yy142;
			default:	goto yy30;
			}
yy9:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'Y':
			case 'y':	goto yy134;
			default:	goto yy30;
			}
yy10:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'B':
			case 'b':	goto yy124;
			case 'I':
			case 'i':	goto yy126;
			default:	goto yy30;
			}
yy11:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'B':
			case 'b':	goto yy114;
			case 'E':
			case 'e':	goto yy116;
			default:	goto yy30;
			}
yy12:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'N':
			case 'n':	goto yy97;
			case 'W':
			case 'w':	goto yy98;
			default:	goto yy30;
			}
yy13:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'H':
			case 'h':	goto yy79;
			case 'R':
			case 'r':	goto yy80;
			default:	goto yy30;
			}
yy14:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'I':
			case 'i':	goto yy70;
			default:	goto yy30;
			}
yy15:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'I':
			case 'i':	goto yy66;
			default:	goto yy30;
			}
yy16:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'I':
			case 'i':	goto yy62;
			default:	goto yy30;
			}
yy17:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'I':
			case 'i':	goto yy58;
			default:	goto yy30;
			}
yy18:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'M':
			case 'm':	goto yy43;
			case 'X':
			case 'x':	goto yy44;
			default:	goto yy30;
			}
yy19:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'E':
			case 'e':	goto yy35;
			default:	goto yy30;
			}
yy20:
			++YYCURSOR;
			yych = *YYCURSOR;
			goto yy34;
yy21:
#line 214 "/home/weyrick/workspace/efind/src/scanner.re"
			{
                    token->tokType = TOKEN_WS;
                    return 0;
                }
#line 293 "/home/weyrick/workspace/efind/src/scanner.c"
yy22:
			++YYCURSOR;
			switch ((yych = *YYCURSOR)) {
			case '*':
			case '-':
			case '.':
			case '/':
			case '?':
			case 'A':
			case 'B':
			case 'C':
			case 'D':
			case 'E':
			case 'F':
			case 'G':
			case 'H':
			case 'I':
			case 'J':
			case 'K':
			case 'L':
			case 'M':
			case 'N':
			case 'O':
			case 'P':
			case 'Q':
			case 'R':
			case 'S':
			case 'T':
			case 'U':
			case 'V':
			case 'W':
			case 'X':
			case 'Y':
			case 'Z':
			case '_':
			case 'a':
			case 'b':
			case 'c':
			case 'd':
			case 'e':
			case 'f':
			case 'g':
			case 'h':
			case 'i':
			case 'j':
			case 'k':
			case 'l':
			case 'm':
			case 'n':
			case 'o':
			case 'p':
			case 'q':
			case 'r':
			case 's':
			case 't':
			case 'u':
			case 'v':
			case 'w':
			case 'x':
			case 'y':
			case 'z':	goto yy29;
			case '0':
			case '1':
			case '2':
			case '3':
			case '4':
			case '5':
			case '6':
			case '7':
			case '8':
			case '9':	goto yy31;
			default:	goto yy23;
			}
yy23:
#line 219 "/home/weyrick/workspace/efind/src/scanner.re"
			{
                    token->tokType = TOKEN_INT;
                    token->data = strndup(q, YYCURSOR - q);
                    return 0;
                }
#line 374 "/home/weyrick/workspace/efind/src/scanner.c"
yy24:
			yych = *++YYCURSOR;
			goto yy30;
yy25:
			++YYCURSOR;
#line 231 "/home/weyrick/workspace/efind/src/scanner.re"
			{ r = SCANNER_RETCODE_EOF; break; }
#line 382 "/home/weyrick/workspace/efind/src/scanner.c"
yy27:
			++YYCURSOR;
#line 233 "/home/weyrick/workspace/efind/src/scanner.re"
			{ r = SCANNER_RETCODE_ERR; break; }
#line 387 "/home/weyrick/workspace/efind/src/scanner.c"
yy29:
			++YYCURSOR;
			yych = *YYCURSOR;
yy30:
			switch (yych) {
			case '*':
			case '-':
			case '.':
			case '/':
			case '0':
			case '1':
			case '2':
			case '3':
			case '4':
			case '5':
			case '6':
			case '7':
			case '8':
			case '9':
			case '?':
			case 'A':
			case 'B':
			case 'C':
			case 'D':
			case 'E':
			case 'F':
			case 'G':
			case 'H':
			case 'I':
			case 'J':
			case 'K':
			case 'L':
			case 'M':
			case 'N':
			case 'O':
			case 'P':
			case 'Q':
			case 'R':
			case 'S':
			case 'T':
			case 'U':
			case 'V':
			case 'W':
			case 'X':
			case 'Y':
			case 'Z':
			case '_':
			case 'a':
			case 'b':
			case 'c':
			case 'd':
			case 'e':
			case 'f':
			case 'g':
			case 'h':
			case 'i':
			case 'j':
			case 'k':
			case 'l':
			case 'm':
			case 'n':
			case 'o':
			case 'p':
			case 'q':
			case 'r':
			case 's':
			case 't':
			case 'u':
			case 'v':
			case 'w':
			case 'x':
			case 'y':
			case 'z':	goto yy29;
			default:	goto yy3;
			}
yy31:
			++YYCURSOR;
			yych = *YYCURSOR;
			switch (yych) {
			case '*':
			case '-':
			case '.':
			case '/':
			case '?':
			case 'A':
			case 'B':
			case 'C':
			case 'D':
			case 'E':
			case 'F':
			case 'G':
			case 'H':
			case 'I':
			case 'J':
			case 'K':
			case 'L':
			case 'M':
			case 'N':
			case 'O':
			case 'P':
			case 'Q':
			case 'R':
			case 'S':
			case 'T':
			case 'U':
			case 'V':
			case 'W':
			case 'X':
			case 'Y':
			case 'Z':
			case '_':
			case 'a':
			case 'b':
			case 'c':
			case 'd':
			case 'e':
			case 'f':
			case 'g':
			case 'h':
			case 'i':
			case 'j':
			case 'k':
			case 'l':
			case 'm':
			case 'n':
			case 'o':
			case 'p':
			case 'q':
			case 'r':
			case 's':
			case 't':
			case 'u':
			case 'v':
			case 'w':
			case 'x':
			case 'y':
			case 'z':	goto yy29;
			case '0':
			case '1':
			case '2':
			case '3':
			case '4':
			case '5':
			case '6':
			case '7':
			case '8':
			case '9':	goto yy31;
			default:	goto yy23;
			}
yy33:
			++YYCURSOR;
			yych = *YYCURSOR;
yy34:
			switch (yych) {
			case '\t':
			case '\n':
			case '\r':
			case ' ':	goto yy33;
			default:	goto yy21;
			}
yy35:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'A':
			case 'a':	goto yy36;
			default:	goto yy30;
			}
yy36:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'D':
			case 'd':	goto yy37;
			default:	goto yy30;
			}
yy37:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'A':
			case 'a':	goto yy38;
			default:	goto yy30;
			}
yy38:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'B':
			case 'b':	goto yy39;
			default:	goto yy30;
			}
yy39:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'L':
			case 'l':	goto yy40;
			default:	goto yy30;
			}
yy40:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'E':
			case 'e':	goto yy41;
			default:	goto yy30;
			}
yy41:
			++YYCURSOR;
			switch ((yych = *YYCURSOR)) {
			case '*':
			case '-':
			case '.':
			case '/':
			case '0':
			case '1':
			case '2':
			case '3':
			case '4':
			case '5':
			case '6':
			case '7':
			case '8':
			case '9':
			case '?':
			case 'A':
			case 'B':
			case 'C':
			case 'D':
			case 'E':
			case 'F':
			case 'G':
			case 'H':
			case 'I':
			case 'J':
			case 'K':
			case 'L':
			case 'M':
			case 'N':
			case 'O':
			case 'P':
			case 'Q':
			case 'R':
			case 'S':
			case 'T':
			case 'U':
			case 'V':
			case 'W':
			case 'X':
			case 'Y':
			case 'Z':
			case '_':
			case 'a':
			case 'b':
			case 'c':
			case 'd':
			case 'e':
			case 'f':
			case 'g':
			case 'h':
			case 'i':
			case 'j':
			case 'k':
			case 'l':
			case 'm':
			case 'n':
			case 'o':
			case 'p':
			case 'q':
			case 'r':
			case 's':
			case 't':
			case 'u':
			case 'v':
			case 'w':
			case 'x':
			case 'y':
			case 'z':	goto yy29;
			default:	goto yy42;
			}
yy42:
#line 202 "/home/weyrick/workspace/efind/src/scanner.re"
			{
                    token->tokType = TOKEN_UNARY;
                    token->opt = 4; // readable
                    return 0;
                }
#line 670 "/home/weyrick/workspace/efind/src/scanner.c"
yy43:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'P':
			case 'p':	goto yy54;
			default:	goto yy30;
			}
yy44:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'E':
			case 'e':	goto yy45;
			default:	goto yy30;
			}
yy45:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'C':
			case 'c':	goto yy46;
			default:	goto yy30;
			}
yy46:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'U':
			case 'u':	goto yy47;
			default:	goto yy30;
			}
yy47:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'T':
			case 't':	goto yy48;
			default:	goto yy30;
			}
yy48:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'A':
			case 'a':	goto yy49;
			default:	goto yy30;
			}
yy49:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'B':
			case 'b':	goto yy50;
			default:	goto yy30;
			}
yy50:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'L':
			case 'l':	goto yy51;
			default:	goto yy30;
			}
yy51:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'E':
			case 'e':	goto yy52;
			default:	goto yy30;
			}
yy52:
			++YYCURSOR;
			switch ((yych = *YYCURSOR)) {
			case '*':
			case '-':
			case '.':
			case '/':
			case '0':
			case '1':
			case '2':
			case '3':
			case '4':
			case '5':
			case '6':
			case '7':
			case '8':
			case '9':
			case '?':
			case 'A':
			case 'B':
			case 'C':
			case 'D':
			case 'E':
			case 'F':
			case 'G':
			case 'H':
			case 'I':
			case 'J':
			case 'K':
			case 'L':
			case 'M':
			case 'N':
			case 'O':
			case 'P':
			case 'Q':
			case 'R':
			case 'S':
			case 'T':
			case 'U':
			case 'V':
			case 'W':
			case 'X':
			case 'Y':
			case 'Z':
			case '_':
			case 'a':
			case 'b':
			case 'c':
			case 'd':
			case 'e':
			case 'f':
			case 'g':
			case 'h':
			case 'i':
			case 'j':
			case 'k':
			case 'l':
			case 'm':
			case 'n':
			case 'o':
			case 'p':
			case 'q':
			case 'r':
			case 's':
			case 't':
			case 'u':
			case 'v':
			case 'w':
			case 'x':
			case 'y':
			case 'z':	goto yy29;
			default:	goto yy53;
			}
yy53:
#line 178 "/home/weyrick/workspace/efind/src/scanner.re"
			{
                    token->tokType = TOKEN_UNARY;
                    token->opt = 0; // executable
                    return 0;
                }
#line 814 "/home/weyrick/workspace/efind/src/scanner.c"
yy54:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'T':
			case 't':	goto yy55;
			default:	goto yy30;
			}
yy55:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'Y':
			case 'y':	goto yy56;
			default:	goto yy30;
			}
yy56:
			++YYCURSOR;
			switch ((yych = *YYCURSOR)) {
			case '*':
			case '-':
			case '.':
			case '/':
			case '0':
			case '1':
			case '2':
			case '3':
			case '4':
			case '5':
			case '6':
			case '7':
			case '8':
			case '9':
			case '?':
			case 'A':
			case 'B':
			case 'C':
			case 'D':
			case 'E':
			case 'F':
			case 'G':
			case 'H':
			case 'I':
			case 'J':
			case 'K':
			case 'L':
			case 'M':
			case 'N':
			case 'O':
			case 'P':
			case 'Q':
			case 'R':
			case 'S':
			case 'T':
			case 'U':
			case 'V':
			case 'W':
			case 'X':
			case 'Y':
			case 'Z':
			case '_':
			case 'a':
			case 'b':
			case 'c':
			case 'd':
			case 'e':
			case 'f':
			case 'g':
			case 'h':
			case 'i':
			case 'j':
			case 'k':
			case 'l':
			case 'm':
			case 'n':
			case 'o':
			case 'p':
			case 'q':
			case 'r':
			case 's':
			case 't':
			case 'u':
			case 'v':
			case 'w':
			case 'x':
			case 'y':
			case 'z':	goto yy29;
			default:	goto yy57;
			}
yy57:
#line 184 "/home/weyrick/workspace/efind/src/scanner.re"
			{
                    token->tokType = TOKEN_UNARY;
                    token->opt = 1; // empty
                    return 0;
                }
#line 909 "/home/weyrick/workspace/efind/src/scanner.c"
yy58:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'N':
			case 'n':	goto yy59;
			default:	goto yy30;
			}
yy59:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'K':
			case 'k':	goto yy60;
			default:	goto yy30;
			}
yy60:
			++YYCURSOR;
			switch ((yych = *YYCURSOR)) {
			case '*':
			case '-':
			case '.':
			case '/':
			case '0':
			case '1':
			case '2':
			case '3':
			case '4':
			case '5':
			case '6':
			case '7':
			case '8':
			case '9':
			case '?':
			case 'A':
			case 'B':
			case 'C':
			case 'D':
			case 'E':
			case 'F':
			case 'G':
			case 'H':
			case 'I':
			case 'J':
			case 'K':
			case 'L':
			case 'M':
			case 'N':
			case 'O':
			case 'P':
			case 'Q':
			case 'R':
			case 'S':
			case 'T':
			case 'U':
			case 'V':
			case 'W':
			case 'X':
			case 'Y':
			case 'Z':
			case '_':
			case 'a':
			case 'b':
			case 'c':
			case 'd':
			case 'e':
			case 'f':
			case 'g':
			case 'h':
			case 'i':
			case 'j':
			case 'k':
			case 'l':
			case 'm':
			case 'n':
			case 'o':
			case 'p':
			case 'q':
			case 'r':
			case 's':
			case 't':
			case 'u':
			case 'v':
			case 'w':
			case 'x':
			case 'y':
			case 'z':	goto yy29;
			default:	goto yy61;
			}
yy61:
#line 166 "/home/weyrick/workspace/efind/src/scanner.re"
			{
                    token->tokType = TOKEN_FTYPE;
                    token->opt = 3; // link
                    return 0;
                }
#line 1004 "/home/weyrick/workspace/efind/src/scanner.c"
yy62:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'L':
			case 'l':	goto yy63;
			default:	goto yy30;
			}
yy63:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'E':
			case 'e':	goto yy64;
			default:	goto yy30;
			}
yy64:
			++YYCURSOR;
			switch ((yych = *YYCURSOR)) {
			case '*':
			case '-':
			case '.':
			case '/':
			case '0':
			case '1':
			case '2':
			case '3':
			case '4':
			case '5':
			case '6':
			case '7':
			case '8':
			case '9':
			case '?':
			case 'A':
			case 'B':
			case 'C':
			case 'D':
			case 'E':
			case 'F':
			case 'G':
			case 'H':
			case 'I':
			case 'J':
			case 'K':
			case 'L':
			case 'M':
			case 'N':
			case 'O':
			case 'P':
			case 'Q':
			case 'R':
			case 'S':
			case 'T':
			case 'U':
			case 'V':
			case 'W':
			case 'X':
			case 'Y':
			case 'Z':
			case '_':
			case 'a':
			case 'b':
			case 'c':
			case 'd':
			case 'e':
			case 'f':
			case 'g':
			case 'h':
			case 'i':
			case 'j':
			case 'k':
			case 'l':
			case 'm':
			case 'n':
			case 'o':
			case 'p':
			case 'q':
			case 'r':
			case 's':
			case 't':
			case 'u':
			case 'v':
			case 'w':
			case 'x':
			case 'y':
			case 'z':	goto yy29;
			default:	goto yy65;
			}
yy65:
#line 160 "/home/weyrick/workspace/efind/src/scanner.re"
			{
                    token->tokType = TOKEN_FTYPE;
                    token->opt = 2; // file
                    return 0;
                }
#line 1099 "/home/weyrick/workspace/efind/src/scanner.c"
yy66:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'P':
			case 'p':	goto yy67;
			default:	goto yy30;
			}
yy67:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'E':
			case 'e':	goto yy68;
			default:	goto yy30;
			}
yy68:
			++YYCURSOR;
			switch ((yych = *YYCURSOR)) {
			case '*':
			case '-':
			case '.':
			case '/':
			case '0':
			case '1':
			case '2':
			case '3':
			case '4':
			case '5':
			case '6':
			case '7':
			case '8':
			case '9':
			case '?':
			case 'A':
			case 'B':
			case 'C':
			case 'D':
			case 'E':
			case 'F':
			case 'G':
			case 'H':
			case 'I':
			case 'J':
			case 'K':
			case 'L':
			case 'M':
			case 'N':
			case 'O':
			case 'P':
			case 'Q':
			case 'R':
			case 'S':
			case 'T':
			case 'U':
			case 'V':
			case 'W':
			case 'X':
			case 'Y':
			case 'Z':
			case '_':
			case 'a':
			case 'b':
			case 'c':
			case 'd':
			case 'e':
			case 'f':
			case 'g':
			case 'h':
			case 'i':
			case 'j':
			case 'k':
			case 'l':
			case 'm':
			case 'n':
			case 'o':
			case 'p':
			case 'q':
			case 'r':
			case 's':
			case 't':
			case 'u':
			case 'v':
			case 'w':
			case 'x':
			case 'y':
			case 'z':	goto yy29;
			default:	goto yy69;
			}
yy69:
#line 154 "/home/weyrick/workspace/efind/src/scanner.re"
			{
                    token->tokType = TOKEN_FTYPE;
                    token->opt = 1; // pipe
                    return 0;
                }
#line 1194 "/home/weyrick/workspace/efind/src/scanner.c"
yy70:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'R':
			case 'r':	goto yy71;
			default:	goto yy30;
			}
yy71:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'E':
			case 'e':	goto yy72;
			default:	goto yy30;
			}
yy72:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'C':
			case 'c':	goto yy73;
			default:	goto yy30;
			}
yy73:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'T':
			case 't':	goto yy74;
			default:	goto yy30;
			}
yy74:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'O':
			case 'o':	goto yy75;
			default:	goto yy30;
			}
yy75:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'R':
			case 'r':	goto yy76;
			default:	goto yy30;
			}
yy76:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'Y':
			case 'y':	goto yy77;
			default:	goto yy30;
			}
yy77:
			++YYCURSOR;
			switch ((yych = *YYCURSOR)) {
			case '*':
			case '-':
			case '.':
			case '/':
			case '0':
			case '1':
			case '2':
			case '3':
			case '4':
			case '5':
			case '6':
			case '7':
			case '8':
			case '9':
			case '?':
			case 'A':
			case 'B':
			case 'C':
			case 'D':
			case 'E':
			case 'F':
			case 'G':
			case 'H':
			case 'I':
			case 'J':
			case 'K':
			case 'L':
			case 'M':
			case 'N':
			case 'O':
			case 'P':
			case 'Q':
			case 'R':
			case 'S':
			case 'T':
			case 'U':
			case 'V':
			case 'W':
			case 'X':
			case 'Y':
			case 'Z':
			case '_':
			case 'a':
			case 'b':
			case 'c':
			case 'd':
			case 'e':
			case 'f':
			case 'g':
			case 'h':
			case 'i':
			case 'j':
			case 'k':
			case 'l':
			case 'm':
			case 'n':
			case 'o':
			case 'p':
			case 'q':
			case 'r':
			case 's':
			case 't':
			case 'u':
			case 'v':
			case 'w':
			case 'x':
			case 'y':
			case 'z':	goto yy29;
			default:	goto yy78;
			}
yy78:
#line 148 "/home/weyrick/workspace/efind/src/scanner.re"
			{
                    token->tokType = TOKEN_FTYPE;
                    token->opt = 0; // directory
                    return 0;
                }
#line 1324 "/home/weyrick/workspace/efind/src/scanner.c"
yy79:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'O':
			case 'o':	goto yy88;
			default:	goto yy30;
			}
yy80:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'I':
			case 'i':	goto yy81;
			default:	goto yy30;
			}
yy81:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'T':
			case 't':	goto yy82;
			default:	goto yy30;
			}
yy82:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'A':
			case 'a':	goto yy83;
			default:	goto yy30;
			}
yy83:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'B':
			case 'b':	goto yy84;
			default:	goto yy30;
			}
yy84:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'L':
			case 'l':	goto yy85;
			default:	goto yy30;
			}
yy85:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'E':
			case 'e':	goto yy86;
			default:	goto yy30;
			}
yy86:
			++YYCURSOR;
			switch ((yych = *YYCURSOR)) {
			case '*':
			case '-':
			case '.':
			case '/':
			case '0':
			case '1':
			case '2':
			case '3':
			case '4':
			case '5':
			case '6':
			case '7':
			case '8':
			case '9':
			case '?':
			case 'A':
			case 'B':
			case 'C':
			case 'D':
			case 'E':
			case 'F':
			case 'G':
			case 'H':
			case 'I':
			case 'J':
			case 'K':
			case 'L':
			case 'M':
			case 'N':
			case 'O':
			case 'P':
			case 'Q':
			case 'R':
			case 'S':
			case 'T':
			case 'U':
			case 'V':
			case 'W':
			case 'X':
			case 'Y':
			case 'Z':
			case '_':
			case 'a':
			case 'b':
			case 'c':
			case 'd':
			case 'e':
			case 'f':
			case 'g':
			case 'h':
			case 'i':
			case 'j':
			case 'k':
			case 'l':
			case 'm':
			case 'n':
			case 'o':
			case 'p':
			case 'q':
			case 'r':
			case 's':
			case 't':
			case 'u':
			case 'v':
			case 'w':
			case 'x':
			case 'y':
			case 'z':	goto yy29;
			default:	goto yy87;
			}
yy87:
#line 208 "/home/weyrick/workspace/efind/src/scanner.re"
			{
                    token->tokType = TOKEN_UNARY;
                    token->opt = 5; // writable
                    return 0;
                }
#line 1454 "/home/weyrick/workspace/efind/src/scanner.c"
yy88:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'L':
			case 'l':	goto yy89;
			default:	goto yy30;
			}
yy89:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'E':
			case 'e':	goto yy90;
			default:	goto yy30;
			}
yy90:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'N':
			case 'n':	goto yy91;
			default:	goto yy30;
			}
yy91:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'A':
			case 'a':	goto yy92;
			default:	goto yy30;
			}
yy92:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'M':
			case 'm':	goto yy93;
			default:	goto yy30;
			}
yy93:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'E':
			case 'e':	goto yy94;
			default:	goto yy30;
			}
yy94:
			++YYCURSOR;
			yych = *YYCURSOR;
			switch (yych) {
			case '*':
			case '-':
			case '.':
			case '/':
			case '0':
			case '1':
			case '2':
			case '3':
			case '4':
			case '5':
			case '6':
			case '7':
			case '8':
			case '9':
			case '?':
			case 'A':
			case 'B':
			case 'C':
			case 'E':
			case 'F':
			case 'G':
			case 'H':
			case 'I':
			case 'J':
			case 'K':
			case 'L':
			case 'M':
			case 'N':
			case 'O':
			case 'P':
			case 'Q':
			case 'R':
			case 'S':
			case 'T':
			case 'U':
			case 'V':
			case 'W':
			case 'X':
			case 'Y':
			case 'Z':
			case '_':
			case 'a':
			case 'b':
			case 'c':
			case 'e':
			case 'f':
			case 'g':
			case 'h':
			case 'i':
			case 'j':
			case 'k':
			case 'l':
			case 'm':
			case 'n':
			case 'o':
			case 'p':
			case 'q':
			case 'r':
			case 's':
			case 't':
			case 'u':
			case 'v':
			case 'w':
			case 'x':
			case 'y':
			case 'z':	goto yy29;
			case 'D':
			case 'd':	goto yy94;
			default:	goto yy96;
			}
yy96:
#line 136 "/home/weyrick/workspace/efind/src/scanner.re"
			{
                    token->tokType = TOKEN_NAMED;
                    token->opt = 2; // wholename
                    return 0;
                }
#line 1578 "/home/weyrick/workspace/efind/src/scanner.c"
yy97:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'A':
			case 'a':	goto yy109;
			default:	goto yy30;
			}
yy98:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'H':
			case 'h':	goto yy99;
			default:	goto yy30;
			}
yy99:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'O':
			case 'o':	goto yy100;
			default:	goto yy30;
			}
yy100:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'L':
			case 'l':	goto yy101;
			default:	goto yy30;
			}
yy101:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'E':
			case 'e':	goto yy102;
			default:	goto yy30;
			}
yy102:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'N':
			case 'n':	goto yy103;
			default:	goto yy30;
			}
yy103:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'A':
			case 'a':	goto yy104;
			default:	goto yy30;
			}
yy104:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'M':
			case 'm':	goto yy105;
			default:	goto yy30;
			}
yy105:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'E':
			case 'e':	goto yy106;
			default:	goto yy30;
			}
yy106:
			++YYCURSOR;
			yych = *YYCURSOR;
			switch (yych) {
			case '*':
			case '-':
			case '.':
			case '/':
			case '0':
			case '1':
			case '2':
			case '3':
			case '4':
			case '5':
			case '6':
			case '7':
			case '8':
			case '9':
			case '?':
			case 'A':
			case 'B':
			case 'C':
			case 'E':
			case 'F':
			case 'G':
			case 'H':
			case 'I':
			case 'J':
			case 'K':
			case 'L':
			case 'M':
			case 'N':
			case 'O':
			case 'P':
			case 'Q':
			case 'R':
			case 'S':
			case 'T':
			case 'U':
			case 'V':
			case 'W':
			case 'X':
			case 'Y':
			case 'Z':
			case '_':
			case 'a':
			case 'b':
			case 'c':
			case 'e':
			case 'f':
			case 'g':
			case 'h':
			case 'i':
			case 'j':
			case 'k':
			case 'l':
			case 'm':
			case 'n':
			case 'o':
			case 'p':
			case 'q':
			case 'r':
			case 's':
			case 't':
			case 'u':
			case 'v':
			case 'w':
			case 'x':
			case 'y':
			case 'z':	goto yy29;
			case 'D':
			case 'd':	goto yy106;
			default:	goto yy108;
			}
yy108:
#line 142 "/home/weyrick/workspace/efind/src/scanner.re"
			{
                    token->tokType = TOKEN_NAMED;
                    token->opt = 3; // iwholename
                    return 0;
                }
#line 1723 "/home/weyrick/workspace/efind/src/scanner.c"
yy109:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'M':
			case 'm':	goto yy110;
			default:	goto yy30;
			}
yy110:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'E':
			case 'e':	goto yy111;
			default:	goto yy30;
			}
yy111:
			++YYCURSOR;
			yych = *YYCURSOR;
			switch (yych) {
			case '*':
			case '-':
			case '.':
			case '/':
			case '0':
			case '1':
			case '2':
			case '3':
			case '4':
			case '5':
			case '6':
			case '7':
			case '8':
			case '9':
			case '?':
			case 'A':
			case 'B':
			case 'C':
			case 'E':
			case 'F':
			case 'G':
			case 'H':
			case 'I':
			case 'J':
			case 'K':
			case 'L':
			case 'M':
			case 'N':
			case 'O':
			case 'P':
			case 'Q':
			case 'R':
			case 'S':
			case 'T':
			case 'U':
			case 'V':
			case 'W':
			case 'X':
			case 'Y':
			case 'Z':
			case '_':
			case 'a':
			case 'b':
			case 'c':
			case 'e':
			case 'f':
			case 'g':
			case 'h':
			case 'i':
			case 'j':
			case 'k':
			case 'l':
			case 'm':
			case 'n':
			case 'o':
			case 'p':
			case 'q':
			case 'r':
			case 's':
			case 't':
			case 'u':
			case 'v':
			case 'w':
			case 'x':
			case 'y':
			case 'z':	goto yy29;
			case 'D':
			case 'd':	goto yy111;
			default:	goto yy113;
			}
yy113:
#line 130 "/home/weyrick/workspace/efind/src/scanner.re"
			{
                    token->tokType = TOKEN_NAMED;
                    token->opt = 1; // iname
                    return 0;
                }
#line 1819 "/home/weyrick/workspace/efind/src/scanner.c"
yy114:
			++YYCURSOR;
			switch ((yych = *YYCURSOR)) {
			case '*':
			case '-':
			case '.':
			case '/':
			case '0':
			case '1':
			case '2':
			case '3':
			case '4':
			case '5':
			case '6':
			case '7':
			case '8':
			case '9':
			case '?':
			case 'A':
			case 'B':
			case 'C':
			case 'D':
			case 'E':
			case 'F':
			case 'G':
			case 'H':
			case 'I':
			case 'J':
			case 'K':
			case 'L':
			case 'M':
			case 'N':
			case 'O':
			case 'P':
			case 'Q':
			case 'R':
			case 'S':
			case 'T':
			case 'U':
			case 'V':
			case 'W':
			case 'X':
			case 'Y':
			case 'Z':
			case '_':
			case 'a':
			case 'b':
			case 'c':
			case 'd':
			case 'e':
			case 'f':
			case 'g':
			case 'h':
			case 'i':
			case 'j':
			case 'k':
			case 'l':
			case 'm':
			case 'n':
			case 'o':
			case 'p':
			case 'q':
			case 'r':
			case 's':
			case 't':
			case 'u':
			case 'v':
			case 'w':
			case 'x':
			case 'y':
			case 'z':	goto yy29;
			default:	goto yy115;
			}
yy115:
#line 102 "/home/weyrick/workspace/efind/src/scanner.re"
			{
                    token->tokType = TOKEN_SIZEQUAL;
                    token->opt = 'M';
                    return 0;
                }
#line 1900 "/home/weyrick/workspace/efind/src/scanner.c"
yy116:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'G':
			case 'g':	goto yy117;
			default:	goto yy30;
			}
yy117:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'A':
			case 'a':	goto yy118;
			default:	goto yy30;
			}
yy118:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'B':
			case 'b':	goto yy119;
			default:	goto yy30;
			}
yy119:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'Y':
			case 'y':	goto yy120;
			default:	goto yy30;
			}
yy120:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'T':
			case 't':	goto yy121;
			default:	goto yy30;
			}
yy121:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'E':
			case 'e':	goto yy122;
			default:	goto yy30;
			}
yy122:
			++YYCURSOR;
			yych = *YYCURSOR;
			switch (yych) {
			case '*':
			case '-':
			case '.':
			case '/':
			case '0':
			case '1':
			case '2':
			case '3':
			case '4':
			case '5':
			case '6':
			case '7':
			case '8':
			case '9':
			case '?':
			case 'A':
			case 'B':
			case 'C':
			case 'D':
			case 'E':
			case 'F':
			case 'G':
			case 'H':
			case 'I':
			case 'J':
			case 'K':
			case 'L':
			case 'M':
			case 'N':
			case 'O':
			case 'P':
			case 'Q':
			case 'R':
			case 'T':
			case 'U':
			case 'V':
			case 'W':
			case 'X':
			case 'Y':
			case 'Z':
			case '_':
			case 'a':
			case 'b':
			case 'c':
			case 'd':
			case 'e':
			case 'f':
			case 'g':
			case 'h':
			case 'i':
			case 'j':
			case 'k':
			case 'l':
			case 'm':
			case 'n':
			case 'o':
			case 'p':
			case 'q':
			case 'r':
			case 't':
			case 'u':
			case 'v':
			case 'w':
			case 'x':
			case 'y':
			case 'z':	goto yy29;
			case 'S':
			case 's':	goto yy122;
			default:	goto yy115;
			}
yy124:
			++YYCURSOR;
			switch ((yych = *YYCURSOR)) {
			case '*':
			case '-':
			case '.':
			case '/':
			case '0':
			case '1':
			case '2':
			case '3':
			case '4':
			case '5':
			case '6':
			case '7':
			case '8':
			case '9':
			case '?':
			case 'A':
			case 'B':
			case 'C':
			case 'D':
			case 'E':
			case 'F':
			case 'G':
			case 'H':
			case 'I':
			case 'J':
			case 'K':
			case 'L':
			case 'M':
			case 'N':
			case 'O':
			case 'P':
			case 'Q':
			case 'R':
			case 'S':
			case 'T':
			case 'U':
			case 'V':
			case 'W':
			case 'X':
			case 'Y':
			case 'Z':
			case '_':
			case 'a':
			case 'b':
			case 'c':
			case 'd':
			case 'e':
			case 'f':
			case 'g':
			case 'h':
			case 'i':
			case 'j':
			case 'k':
			case 'l':
			case 'm':
			case 'n':
			case 'o':
			case 'p':
			case 'q':
			case 'r':
			case 's':
			case 't':
			case 'u':
			case 'v':
			case 'w':
			case 'x':
			case 'y':
			case 'z':	goto yy29;
			default:	goto yy125;
			}
yy125:
#line 96 "/home/weyrick/workspace/efind/src/scanner.re"
			{
                    token->tokType = TOKEN_SIZEQUAL;
                    token->opt = 'k';
                    return 0;
                }
#line 2097 "/home/weyrick/workspace/efind/src/scanner.c"
yy126:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'L':
			case 'l':	goto yy127;
			default:	goto yy30;
			}
yy127:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'O':
			case 'o':	goto yy128;
			default:	goto yy30;
			}
yy128:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'B':
			case 'b':	goto yy129;
			default:	goto yy30;
			}
yy129:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'Y':
			case 'y':	goto yy130;
			default:	goto yy30;
			}
yy130:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'T':
			case 't':	goto yy131;
			default:	goto yy30;
			}
yy131:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'E':
			case 'e':	goto yy132;
			default:	goto yy30;
			}
yy132:
			++YYCURSOR;
			yych = *YYCURSOR;
			switch (yych) {
			case '*':
			case '-':
			case '.':
			case '/':
			case '0':
			case '1':
			case '2':
			case '3':
			case '4':
			case '5':
			case '6':
			case '7':
			case '8':
			case '9':
			case '?':
			case 'A':
			case 'B':
			case 'C':
			case 'D':
			case 'E':
			case 'F':
			case 'G':
			case 'H':
			case 'I':
			case 'J':
			case 'K':
			case 'L':
			case 'M':
			case 'N':
			case 'O':
			case 'P':
			case 'Q':
			case 'R':
			case 'T':
			case 'U':
			case 'V':
			case 'W':
			case 'X':
			case 'Y':
			case 'Z':
			case '_':
			case 'a':
			case 'b':
			case 'c':
			case 'd':
			case 'e':
			case 'f':
			case 'g':
			case 'h':
			case 'i':
			case 'j':
			case 'k':
			case 'l':
			case 'm':
			case 'n':
			case 'o':
			case 'p':
			case 'q':
			case 'r':
			case 't':
			case 'u':
			case 'v':
			case 'w':
			case 'x':
			case 'y':
			case 'z':	goto yy29;
			case 'S':
			case 's':	goto yy132;
			default:	goto yy125;
			}
yy134:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'T':
			case 't':	goto yy135;
			default:	goto yy30;
			}
yy135:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'E':
			case 'e':	goto yy136;
			default:	goto yy30;
			}
yy136:
			++YYCURSOR;
			yych = *YYCURSOR;
			switch (yych) {
			case '*':
			case '-':
			case '.':
			case '/':
			case '0':
			case '1':
			case '2':
			case '3':
			case '4':
			case '5':
			case '6':
			case '7':
			case '8':
			case '9':
			case '?':
			case 'A':
			case 'B':
			case 'C':
			case 'D':
			case 'E':
			case 'F':
			case 'G':
			case 'H':
			case 'I':
			case 'J':
			case 'K':
			case 'L':
			case 'M':
			case 'N':
			case 'O':
			case 'P':
			case 'Q':
			case 'R':
			case 'T':
			case 'U':
			case 'V':
			case 'W':
			case 'X':
			case 'Y':
			case 'Z':
			case '_':
			case 'a':
			case 'b':
			case 'c':
			case 'd':
			case 'e':
			case 'f':
			case 'g':
			case 'h':
			case 'i':
			case 'j':
			case 'k':
			case 'l':
			case 'm':
			case 'n':
			case 'o':
			case 'p':
			case 'q':
			case 'r':
			case 't':
			case 'u':
			case 'v':
			case 'w':
			case 'x':
			case 'y':
			case 'z':	goto yy29;
			case 'S':
			case 's':	goto yy136;
			default:	goto yy138;
			}
yy138:
#line 90 "/home/weyrick/workspace/efind/src/scanner.re"
			{
                    token->tokType = TOKEN_SIZEQUAL;
                    token->opt = 'c';
                    return 0;
                }
#line 2309 "/home/weyrick/workspace/efind/src/scanner.c"
yy139:
			++YYCURSOR;
			switch ((yych = *YYCURSOR)) {
			case '*':
			case '-':
			case '.':
			case '/':
			case '0':
			case '1':
			case '2':
			case '3':
			case '4':
			case '5':
			case '6':
			case '7':
			case '8':
			case '9':
			case '?':
			case 'A':
			case 'B':
			case 'C':
			case 'D':
			case 'E':
			case 'F':
			case 'G':
			case 'H':
			case 'I':
			case 'J':
			case 'K':
			case 'L':
			case 'M':
			case 'N':
			case 'O':
			case 'P':
			case 'Q':
			case 'R':
			case 'S':
			case 'T':
			case 'U':
			case 'V':
			case 'W':
			case 'X':
			case 'Y':
			case 'Z':
			case '_':
			case 'a':
			case 'b':
			case 'c':
			case 'd':
			case 'e':
			case 'f':
			case 'g':
			case 'h':
			case 'i':
			case 'j':
			case 'k':
			case 'l':
			case 'm':
			case 'n':
			case 'o':
			case 'p':
			case 'q':
			case 'r':
			case 's':
			case 't':
			case 'u':
			case 'v':
			case 'w':
			case 'x':
			case 'y':
			case 'z':	goto yy29;
			default:	goto yy140;
			}
yy140:
#line 108 "/home/weyrick/workspace/efind/src/scanner.re"
			{
                    token->tokType = TOKEN_SIZEQUAL;
                    token->opt = 'G';
                    return 0;
                }
#line 2390 "/home/weyrick/workspace/efind/src/scanner.c"
yy141:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'D':
			case 'd':	goto yy153;
			case 'G':
			case 'g':	goto yy155;
			default:	goto yy30;
			}
yy142:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'O':
			case 'o':	goto yy143;
			default:	goto yy30;
			}
yy143:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'U':
			case 'u':	goto yy144;
			default:	goto yy30;
			}
yy144:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'P':
			case 'p':	goto yy145;
			default:	goto yy30;
			}
yy145:
			++YYCURSOR;
			switch ((yych = *YYCURSOR)) {
			case '*':
			case '-':
			case '.':
			case '/':
			case '0':
			case '1':
			case '2':
			case '3':
			case '4':
			case '5':
			case '6':
			case '7':
			case '8':
			case '9':
			case '?':
			case 'A':
			case 'B':
			case 'C':
			case 'D':
			case 'F':
			case 'G':
			case 'H':
			case 'I':
			case 'J':
			case 'K':
			case 'L':
			case 'M':
			case 'N':
			case 'O':
			case 'P':
			case 'Q':
			case 'R':
			case 'S':
			case 'T':
			case 'U':
			case 'V':
			case 'W':
			case 'X':
			case 'Y':
			case 'Z':
			case '_':
			case 'a':
			case 'b':
			case 'c':
			case 'd':
			case 'f':
			case 'g':
			case 'h':
			case 'i':
			case 'j':
			case 'k':
			case 'l':
			case 'm':
			case 'n':
			case 'o':
			case 'p':
			case 'q':
			case 'r':
			case 's':
			case 't':
			case 'u':
			case 'v':
			case 'w':
			case 'x':
			case 'y':
			case 'z':	goto yy29;
			case 'E':
			case 'e':	goto yy147;
			default:	goto yy146;
			}
yy146:
#line 119 "/home/weyrick/workspace/efind/src/scanner.re"
			{
                    token->tokType = TOKEN_GROUPEDBY;
                    return 0;
                }
#line 2500 "/home/weyrick/workspace/efind/src/scanner.c"
yy147:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'D':
			case 'd':	goto yy148;
			default:	goto yy30;
			}
yy148:
			yych = *(YYMARKER = ++YYCURSOR);
			switch (yych) {
			case ' ':	goto yy149;
			default:	goto yy30;
			}
yy149:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'B':
			case 'b':	goto yy151;
			default:	goto yy150;
			}
yy150:
			YYCURSOR = YYMARKER;
			goto yy3;
yy151:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'Y':
			case 'y':	goto yy152;
			default:	goto yy150;
			}
yy152:
			yych = *++YYCURSOR;
			goto yy146;
yy153:
			++YYCURSOR;
			switch ((yych = *YYCURSOR)) {
			case '*':
			case '-':
			case '.':
			case '/':
			case '0':
			case '1':
			case '2':
			case '3':
			case '4':
			case '5':
			case '6':
			case '7':
			case '8':
			case '9':
			case '?':
			case 'A':
			case 'B':
			case 'C':
			case 'D':
			case 'E':
			case 'F':
			case 'G':
			case 'H':
			case 'I':
			case 'J':
			case 'K':
			case 'L':
			case 'M':
			case 'N':
			case 'O':
			case 'P':
			case 'Q':
			case 'R':
			case 'S':
			case 'T':
			case 'U':
			case 'V':
			case 'W':
			case 'X':
			case 'Y':
			case 'Z':
			case '_':
			case 'a':
			case 'b':
			case 'c':
			case 'd':
			case 'e':
			case 'f':
			case 'g':
			case 'h':
			case 'i':
			case 'j':
			case 'k':
			case 'l':
			case 'm':
			case 'n':
			case 'o':
			case 'p':
			case 'q':
			case 'r':
			case 's':
			case 't':
			case 'u':
			case 'v':
			case 'w':
			case 'x':
			case 'y':
			case 'z':	goto yy29;
			default:	goto yy154;
			}
yy154:
#line 85 "/home/weyrick/workspace/efind/src/scanner.re"
			{
                    token->tokType = TOKEN_GID;
                    return 0;
                }
#line 2613 "/home/weyrick/workspace/efind/src/scanner.c"
yy155:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'A':
			case 'a':	goto yy156;
			default:	goto yy30;
			}
yy156:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'B':
			case 'b':	goto yy157;
			default:	goto yy30;
			}
yy157:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'Y':
			case 'y':	goto yy158;
			default:	goto yy30;
			}
yy158:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'T':
			case 't':	goto yy159;
			default:	goto yy30;
			}
yy159:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'E':
			case 'e':	goto yy160;
			default:	goto yy30;
			}
yy160:
			++YYCURSOR;
			yych = *YYCURSOR;
			switch (yych) {
			case '*':
			case '-':
			case '.':
			case '/':
			case '0':
			case '1':
			case '2':
			case '3':
			case '4':
			case '5':
			case '6':
			case '7':
			case '8':
			case '9':
			case '?':
			case 'A':
			case 'B':
			case 'C':
			case 'D':
			case 'E':
			case 'F':
			case 'G':
			case 'H':
			case 'I':
			case 'J':
			case 'K':
			case 'L':
			case 'M':
			case 'N':
			case 'O':
			case 'P':
			case 'Q':
			case 'R':
			case 'T':
			case 'U':
			case 'V':
			case 'W':
			case 'X':
			case 'Y':
			case 'Z':
			case '_':
			case 'a':
			case 'b':
			case 'c':
			case 'd':
			case 'e':
			case 'f':
			case 'g':
			case 'h':
			case 'i':
			case 'j':
			case 'k':
			case 'l':
			case 'm':
			case 'n':
			case 'o':
			case 'p':
			case 'q':
			case 'r':
			case 't':
			case 'u':
			case 'v':
			case 'w':
			case 'x':
			case 'y':
			case 'z':	goto yy29;
			case 'S':
			case 's':	goto yy160;
			default:	goto yy140;
			}
yy162:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'D':
			case 'd':	goto yy163;
			default:	goto yy30;
			}
yy163:
			++YYCURSOR;
			switch ((yych = *YYCURSOR)) {
			case '*':
			case '-':
			case '.':
			case '/':
			case '0':
			case '1':
			case '2':
			case '3':
			case '4':
			case '5':
			case '6':
			case '7':
			case '8':
			case '9':
			case '?':
			case 'A':
			case 'B':
			case 'C':
			case 'D':
			case 'E':
			case 'F':
			case 'G':
			case 'H':
			case 'I':
			case 'J':
			case 'K':
			case 'L':
			case 'M':
			case 'N':
			case 'O':
			case 'P':
			case 'Q':
			case 'R':
			case 'S':
			case 'T':
			case 'U':
			case 'V':
			case 'W':
			case 'X':
			case 'Y':
			case 'Z':
			case '_':
			case 'a':
			case 'b':
			case 'c':
			case 'd':
			case 'e':
			case 'f':
			case 'g':
			case 'h':
			case 'i':
			case 'j':
			case 'k':
			case 'l':
			case 'm':
			case 'n':
			case 'o':
			case 'p':
			case 'q':
			case 'r':
			case 's':
			case 't':
			case 'u':
			case 'v':
			case 'w':
			case 'x':
			case 'y':
			case 'z':	goto yy29;
			default:	goto yy164;
			}
yy164:
#line 80 "/home/weyrick/workspace/efind/src/scanner.re"
			{
                    token->tokType = TOKEN_UID;
                    return 0;
                }
#line 2809 "/home/weyrick/workspace/efind/src/scanner.c"
yy165:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'Z':
			case 'z':	goto yy172;
			default:	goto yy30;
			}
yy166:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'C':
			case 'c':	goto yy167;
			default:	goto yy30;
			}
yy167:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'K':
			case 'k':	goto yy168;
			default:	goto yy30;
			}
yy168:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'E':
			case 'e':	goto yy169;
			default:	goto yy30;
			}
yy169:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'T':
			case 't':	goto yy170;
			default:	goto yy30;
			}
yy170:
			++YYCURSOR;
			switch ((yych = *YYCURSOR)) {
			case '*':
			case '-':
			case '.':
			case '/':
			case '0':
			case '1':
			case '2':
			case '3':
			case '4':
			case '5':
			case '6':
			case '7':
			case '8':
			case '9':
			case '?':
			case 'A':
			case 'B':
			case 'C':
			case 'D':
			case 'E':
			case 'F':
			case 'G':
			case 'H':
			case 'I':
			case 'J':
			case 'K':
			case 'L':
			case 'M':
			case 'N':
			case 'O':
			case 'P':
			case 'Q':
			case 'R':
			case 'S':
			case 'T':
			case 'U':
			case 'V':
			case 'W':
			case 'X':
			case 'Y':
			case 'Z':
			case '_':
			case 'a':
			case 'b':
			case 'c':
			case 'd':
			case 'e':
			case 'f':
			case 'g':
			case 'h':
			case 'i':
			case 'j':
			case 'k':
			case 'l':
			case 'm':
			case 'n':
			case 'o':
			case 'p':
			case 'q':
			case 'r':
			case 's':
			case 't':
			case 'u':
			case 'v':
			case 'w':
			case 'x':
			case 'y':
			case 'z':	goto yy29;
			default:	goto yy171;
			}
yy171:
#line 172 "/home/weyrick/workspace/efind/src/scanner.re"
			{
                    token->tokType = TOKEN_FTYPE;
                    token->opt = 4; // socket
                    return 0;
                }
#line 2925 "/home/weyrick/workspace/efind/src/scanner.c"
yy172:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'E':
			case 'e':	goto yy173;
			default:	goto yy30;
			}
yy173:
			++YYCURSOR;
			switch ((yych = *YYCURSOR)) {
			case '*':
			case '-':
			case '.':
			case '/':
			case '0':
			case '1':
			case '2':
			case '3':
			case '4':
			case '5':
			case '6':
			case '7':
			case '8':
			case '9':
			case '?':
			case 'A':
			case 'B':
			case 'C':
			case 'D':
			case 'E':
			case 'F':
			case 'G':
			case 'H':
			case 'I':
			case 'J':
			case 'K':
			case 'L':
			case 'M':
			case 'N':
			case 'O':
			case 'P':
			case 'Q':
			case 'R':
			case 'S':
			case 'T':
			case 'U':
			case 'V':
			case 'W':
			case 'X':
			case 'Y':
			case 'Z':
			case '_':
			case 'a':
			case 'b':
			case 'c':
			case 'd':
			case 'e':
			case 'f':
			case 'g':
			case 'h':
			case 'i':
			case 'j':
			case 'k':
			case 'l':
			case 'm':
			case 'n':
			case 'o':
			case 'p':
			case 'q':
			case 'r':
			case 's':
			case 't':
			case 'u':
			case 'v':
			case 'w':
			case 'x':
			case 'y':
			case 'z':	goto yy29;
			default:	goto yy174;
			}
yy174:
#line 75 "/home/weyrick/workspace/efind/src/scanner.re"
			{
                    token->tokType = TOKEN_SIZE;
                    return 0;
                }
#line 3012 "/home/weyrick/workspace/efind/src/scanner.c"
yy175:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'M':
			case 'm':	goto yy201;
			default:	goto yy30;
			}
yy176:
			yych = *(YYMARKER = ++YYCURSOR);
			switch (yych) {
			case '\t':
			case '\n':
			case '\r':
			case ' ':	goto yy179;
			case '*':
			case '-':
			case '.':
			case '/':
			case '0':
			case '1':
			case '2':
			case '3':
			case '4':
			case '5':
			case '6':
			case '7':
			case '8':
			case '9':
			case '?':
			case 'A':
			case 'B':
			case 'C':
			case 'D':
			case 'E':
			case 'F':
			case 'H':
			case 'I':
			case 'J':
			case 'K':
			case 'L':
			case 'M':
			case 'N':
			case 'O':
			case 'P':
			case 'Q':
			case 'R':
			case 'S':
			case 'V':
			case 'W':
			case 'X':
			case 'Y':
			case 'Z':
			case '_':
			case 'a':
			case 'b':
			case 'c':
			case 'd':
			case 'e':
			case 'f':
			case 'h':
			case 'i':
			case 'j':
			case 'k':
			case 'l':
			case 'm':
			case 'n':
			case 'o':
			case 'p':
			case 'q':
			case 'r':
			case 's':
			case 'v':
			case 'w':
			case 'x':
			case 'y':
			case 'z':	goto yy29;
			case 'G':
			case 'g':	goto yy181;
			case 'T':
			case 't':	goto yy177;
			case 'U':
			case 'u':	goto yy182;
			default:	goto yy3;
			}
yy177:
			++YYCURSOR;
			switch ((yych = *YYCURSOR)) {
			case '*':
			case '-':
			case '.':
			case '/':
			case '0':
			case '1':
			case '2':
			case '3':
			case '4':
			case '5':
			case '6':
			case '7':
			case '8':
			case '9':
			case '?':
			case 'A':
			case 'B':
			case 'C':
			case 'D':
			case 'E':
			case 'F':
			case 'G':
			case 'H':
			case 'I':
			case 'J':
			case 'K':
			case 'L':
			case 'M':
			case 'N':
			case 'O':
			case 'P':
			case 'Q':
			case 'R':
			case 'S':
			case 'T':
			case 'U':
			case 'V':
			case 'W':
			case 'X':
			case 'Y':
			case 'Z':
			case '_':
			case 'a':
			case 'b':
			case 'c':
			case 'd':
			case 'e':
			case 'f':
			case 'g':
			case 'h':
			case 'i':
			case 'j':
			case 'k':
			case 'l':
			case 'm':
			case 'n':
			case 'o':
			case 'p':
			case 'q':
			case 'r':
			case 's':
			case 't':
			case 'u':
			case 'v':
			case 'w':
			case 'x':
			case 'y':
			case 'z':	goto yy29;
			default:	goto yy178;
			}
yy178:
#line 70 "/home/weyrick/workspace/efind/src/scanner.re"
			{
                    token->tokType = TOKEN_NOT;
                    return 0;
                }
#line 3176 "/home/weyrick/workspace/efind/src/scanner.c"
yy179:
			++YYCURSOR;
			yych = *YYCURSOR;
			switch (yych) {
			case '\t':
			case '\n':
			case '\r':
			case ' ':	goto yy179;
			case 'G':
			case 'g':	goto yy193;
			case 'U':
			case 'u':	goto yy192;
			default:	goto yy150;
			}
yy181:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'R':
			case 'r':	goto yy187;
			default:	goto yy30;
			}
yy182:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'S':
			case 's':	goto yy183;
			default:	goto yy30;
			}
yy183:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'E':
			case 'e':	goto yy184;
			default:	goto yy30;
			}
yy184:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'R':
			case 'r':	goto yy185;
			default:	goto yy30;
			}
yy185:
			++YYCURSOR;
			switch ((yych = *YYCURSOR)) {
			case '*':
			case '-':
			case '.':
			case '/':
			case '0':
			case '1':
			case '2':
			case '3':
			case '4':
			case '5':
			case '6':
			case '7':
			case '8':
			case '9':
			case '?':
			case 'A':
			case 'B':
			case 'C':
			case 'D':
			case 'E':
			case 'F':
			case 'G':
			case 'H':
			case 'I':
			case 'J':
			case 'K':
			case 'L':
			case 'M':
			case 'N':
			case 'O':
			case 'P':
			case 'Q':
			case 'R':
			case 'S':
			case 'T':
			case 'U':
			case 'V':
			case 'W':
			case 'X':
			case 'Y':
			case 'Z':
			case '_':
			case 'a':
			case 'b':
			case 'c':
			case 'd':
			case 'e':
			case 'f':
			case 'g':
			case 'h':
			case 'i':
			case 'j':
			case 'k':
			case 'l':
			case 'm':
			case 'n':
			case 'o':
			case 'p':
			case 'q':
			case 'r':
			case 's':
			case 't':
			case 'u':
			case 'v':
			case 'w':
			case 'x':
			case 'y':
			case 'z':	goto yy29;
			default:	goto yy186;
			}
yy186:
#line 196 "/home/weyrick/workspace/efind/src/scanner.re"
			{
                    token->tokType = TOKEN_UNARY;
                    token->opt = 3; // nouser
                    return 0;
                }
#line 3299 "/home/weyrick/workspace/efind/src/scanner.c"
yy187:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'O':
			case 'o':	goto yy188;
			default:	goto yy30;
			}
yy188:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'U':
			case 'u':	goto yy189;
			default:	goto yy30;
			}
yy189:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'P':
			case 'p':	goto yy190;
			default:	goto yy30;
			}
yy190:
			++YYCURSOR;
			switch ((yych = *YYCURSOR)) {
			case '*':
			case '-':
			case '.':
			case '/':
			case '0':
			case '1':
			case '2':
			case '3':
			case '4':
			case '5':
			case '6':
			case '7':
			case '8':
			case '9':
			case '?':
			case 'A':
			case 'B':
			case 'C':
			case 'D':
			case 'E':
			case 'F':
			case 'G':
			case 'H':
			case 'I':
			case 'J':
			case 'K':
			case 'L':
			case 'M':
			case 'N':
			case 'O':
			case 'P':
			case 'Q':
			case 'R':
			case 'S':
			case 'T':
			case 'U':
			case 'V':
			case 'W':
			case 'X':
			case 'Y':
			case 'Z':
			case '_':
			case 'a':
			case 'b':
			case 'c':
			case 'd':
			case 'e':
			case 'f':
			case 'g':
			case 'h':
			case 'i':
			case 'j':
			case 'k':
			case 'l':
			case 'm':
			case 'n':
			case 'o':
			case 'p':
			case 'q':
			case 'r':
			case 's':
			case 't':
			case 'u':
			case 'v':
			case 'w':
			case 'x':
			case 'y':
			case 'z':	goto yy29;
			default:	goto yy191;
			}
yy191:
#line 190 "/home/weyrick/workspace/efind/src/scanner.re"
			{
                    token->tokType = TOKEN_UNARY;
                    token->opt = 2; // nogroup
                    return 0;
                }
#line 3401 "/home/weyrick/workspace/efind/src/scanner.c"
yy192:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'S':
			case 's':	goto yy198;
			default:	goto yy150;
			}
yy193:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'R':
			case 'r':	goto yy194;
			default:	goto yy150;
			}
yy194:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'O':
			case 'o':	goto yy195;
			default:	goto yy150;
			}
yy195:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'U':
			case 'u':	goto yy196;
			default:	goto yy150;
			}
yy196:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'P':
			case 'p':	goto yy197;
			default:	goto yy150;
			}
yy197:
			yych = *++YYCURSOR;
			goto yy191;
yy198:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'E':
			case 'e':	goto yy199;
			default:	goto yy150;
			}
yy199:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'R':
			case 'r':	goto yy200;
			default:	goto yy150;
			}
yy200:
			yych = *++YYCURSOR;
			goto yy186;
yy201:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'E':
			case 'e':	goto yy202;
			default:	goto yy30;
			}
yy202:
			++YYCURSOR;
			yych = *YYCURSOR;
			switch (yych) {
			case '*':
			case '-':
			case '.':
			case '/':
			case '0':
			case '1':
			case '2':
			case '3':
			case '4':
			case '5':
			case '6':
			case '7':
			case '8':
			case '9':
			case '?':
			case 'A':
			case 'B':
			case 'C':
			case 'E':
			case 'F':
			case 'G':
			case 'H':
			case 'I':
			case 'J':
			case 'K':
			case 'L':
			case 'M':
			case 'N':
			case 'O':
			case 'P':
			case 'Q':
			case 'R':
			case 'S':
			case 'T':
			case 'U':
			case 'V':
			case 'W':
			case 'X':
			case 'Y':
			case 'Z':
			case '_':
			case 'a':
			case 'b':
			case 'c':
			case 'e':
			case 'f':
			case 'g':
			case 'h':
			case 'i':
			case 'j':
			case 'k':
			case 'l':
			case 'm':
			case 'n':
			case 'o':
			case 'p':
			case 'q':
			case 'r':
			case 's':
			case 't':
			case 'u':
			case 'v':
			case 'w':
			case 'x':
			case 'y':
			case 'z':	goto yy29;
			case 'D':
			case 'd':	goto yy202;
			default:	goto yy204;
			}
yy204:
#line 124 "/home/weyrick/workspace/efind/src/scanner.re"
			{
                    token->tokType = TOKEN_NAMED;
                    token->opt = 0; // name
                    return 0;
                }
#line 3545 "/home/weyrick/workspace/efind/src/scanner.c"
yy205:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'D':
			case 'd':	goto yy206;
			default:	goto yy30;
			}
yy206:
			++YYCURSOR;
			switch ((yych = *YYCURSOR)) {
			case '*':
			case '-':
			case '.':
			case '/':
			case '0':
			case '1':
			case '2':
			case '3':
			case '4':
			case '5':
			case '6':
			case '7':
			case '8':
			case '9':
			case '?':
			case 'A':
			case 'B':
			case 'C':
			case 'D':
			case 'E':
			case 'F':
			case 'G':
			case 'H':
			case 'I':
			case 'J':
			case 'K':
			case 'L':
			case 'M':
			case 'N':
			case 'O':
			case 'P':
			case 'Q':
			case 'R':
			case 'S':
			case 'T':
			case 'U':
			case 'V':
			case 'W':
			case 'X':
			case 'Y':
			case 'Z':
			case '_':
			case 'a':
			case 'b':
			case 'c':
			case 'd':
			case 'e':
			case 'f':
			case 'g':
			case 'h':
			case 'i':
			case 'j':
			case 'k':
			case 'l':
			case 'm':
			case 'n':
			case 'o':
			case 'p':
			case 'q':
			case 'r':
			case 's':
			case 't':
			case 'u':
			case 'v':
			case 'w':
			case 'x':
			case 'y':
			case 'z':	goto yy29;
			default:	goto yy207;
			}
yy207:
#line 65 "/home/weyrick/workspace/efind/src/scanner.re"
			{
                    token->tokType = TOKEN_AND;
                    return 0;
                }
#line 3632 "/home/weyrick/workspace/efind/src/scanner.c"
yy208:
			++YYCURSOR;
			switch ((yych = *YYCURSOR)) {
			case '*':
			case '-':
			case '.':
			case '/':
			case '0':
			case '1':
			case '2':
			case '3':
			case '4':
			case '5':
			case '6':
			case '7':
			case '8':
			case '9':
			case '?':
			case 'A':
			case 'B':
			case 'C':
			case 'D':
			case 'E':
			case 'F':
			case 'G':
			case 'H':
			case 'I':
			case 'J':
			case 'K':
			case 'L':
			case 'M':
			case 'N':
			case 'O':
			case 'P':
			case 'Q':
			case 'R':
			case 'S':
			case 'T':
			case 'U':
			case 'V':
			case 'W':
			case 'X':
			case 'Y':
			case 'Z':
			case '_':
			case 'a':
			case 'b':
			case 'c':
			case 'd':
			case 'e':
			case 'f':
			case 'g':
			case 'h':
			case 'i':
			case 'j':
			case 'k':
			case 'l':
			case 'm':
			case 'n':
			case 'o':
			case 'p':
			case 'q':
			case 'r':
			case 's':
			case 't':
			case 'u':
			case 'v':
			case 'w':
			case 'x':
			case 'y':
			case 'z':	goto yy29;
			default:	goto yy209;
			}
yy209:
#line 60 "/home/weyrick/workspace/efind/src/scanner.re"
			{
                    token->tokType = TOKEN_OR;
                    return 0;
                }
#line 3712 "/home/weyrick/workspace/efind/src/scanner.c"
yy210:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'N':
			case 'n':	goto yy211;
			default:	goto yy30;
			}
yy211:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'E':
			case 'e':	goto yy212;
			default:	goto yy30;
			}
yy212:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'D':
			case 'd':	goto yy213;
			case 'R':
			case 'r':	goto yy214;
			default:	goto yy30;
			}
yy213:
			yych = *(YYMARKER = ++YYCURSOR);
			switch (yych) {
			case ' ':	goto yy216;
			default:	goto yy30;
			}
yy214:
			++YYCURSOR;
			switch ((yych = *YYCURSOR)) {
			case '*':
			case '-':
			case '.':
			case '/':
			case '0':
			case '1':
			case '2':
			case '3':
			case '4':
			case '5':
			case '6':
			case '7':
			case '8':
			case '9':
			case '?':
			case 'A':
			case 'B':
			case 'C':
			case 'D':
			case 'E':
			case 'F':
			case 'G':
			case 'H':
			case 'I':
			case 'J':
			case 'K':
			case 'L':
			case 'M':
			case 'N':
			case 'O':
			case 'P':
			case 'Q':
			case 'R':
			case 'S':
			case 'T':
			case 'U':
			case 'V':
			case 'W':
			case 'X':
			case 'Y':
			case 'Z':
			case '_':
			case 'a':
			case 'b':
			case 'c':
			case 'd':
			case 'e':
			case 'f':
			case 'g':
			case 'h':
			case 'i':
			case 'j':
			case 'k':
			case 'l':
			case 'm':
			case 'n':
			case 'o':
			case 'p':
			case 'q':
			case 'r':
			case 's':
			case 't':
			case 'u':
			case 'v':
			case 'w':
			case 'x':
			case 'y':
			case 'z':	goto yy29;
			default:	goto yy215;
			}
yy215:
#line 114 "/home/weyrick/workspace/efind/src/scanner.re"
			{
                    token->tokType = TOKEN_OWNEDBY;
                    return 0;
                }
#line 3821 "/home/weyrick/workspace/efind/src/scanner.c"
yy216:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'B':
			case 'b':	goto yy217;
			default:	goto yy150;
			}
yy217:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'Y':
			case 'y':	goto yy218;
			default:	goto yy150;
			}
yy218:
			++YYCURSOR;
			yych = *YYCURSOR;
			goto yy215;
		}
#line 235 "/home/weyrick/workspace/efind/src/scanner.re"


	}
	return r;
}
