/* Generated by re2c 0.13.5 on Tue Nov 13 07:31:29 2012 */
#line 1 "/Users/sweyrick/workspace/efind/src/scanner.re"
/*

Copyright (c) 2012, Shannon Weyrick <weyrick@mozek.us>
All rights reserved.

Redistribution and use in source and binary forms, with or without
modification, are permitted provided that the following conditions are met:
    * Redistributions of source code must retain the above copyright
      notice, this list of conditions and the following disclaimer.
    * Redistributions in binary form must reproduce the above copyright
      notice, this list of conditions and the following disclaimer in the
      documentation and/or other materials provided with the distribution.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
DISCLAIMED. IN NO EVENT SHALL <COPYRIGHT HOLDER> BE LIABLE FOR ANY
DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
(INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
(INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

*/

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#define _IN_SCANNER
#include "scanner.h"
#if 0
#define DEBUG(stmt) stmt
#else
#define DEBUG(stmt)
#endif

int scan(scanner_state *s, scanner_token *token) {

	int r=SCANNER_RETCODE_IMPOSSIBLE;
    char *q=s->start; //keep initial start

#define YYCTYPE char
#define YYCURSOR (s->start)
#define YYLIMIT (s->end)
#define YYMARKER (s->ptr)
#define YYDEBUG(s, c) printf("state: %d char: %c\n", s, c)

	while(SCANNER_RETCODE_IMPOSSIBLE == r) {
	
		
#line 55 "/Users/sweyrick/workspace/efind/src/scanner.c"
		{
			YYCTYPE yych;

			yych = *YYCURSOR;
			switch (yych) {
			case 0x00:	goto yy27;
			case '\t':
			case '\n':
			case '\r':
			case ' ':	goto yy22;
			case '*':
			case '-':
			case '.':
			case '/':
			case '?':
			case 'C':
			case 'J':
			case 'Q':
			case 'T':
			case 'V':
			case 'X':
			case 'Y':
			case 'Z':
			case '_':
			case 'c':
			case 'j':
			case 'q':
			case 't':
			case 'v':
			case 'x':
			case 'y':
			case 'z':	goto yy26;
			case '0':
			case '1':
			case '2':
			case '3':
			case '4':
			case '5':
			case '6':
			case '7':
			case '8':
			case '9':	goto yy24;
			case 'A':
			case 'a':	goto yy4;
			case 'B':
			case 'b':	goto yy10;
			case 'D':
			case 'd':	goto yy15;
			case 'E':
			case 'e':	goto yy19;
			case 'F':
			case 'f':	goto yy17;
			case 'G':
			case 'g':	goto yy9;
			case 'H':
			case 'h':	goto yy21;
			case 'I':
			case 'i':	goto yy13;
			case 'K':
			case 'k':	goto yy11;
			case 'L':
			case 'l':	goto yy18;
			case 'M':
			case 'm':	goto yy12;
			case 'N':
			case 'n':	goto yy6;
			case 'O':
			case 'o':	goto yy2;
			case 'P':
			case 'p':	goto yy16;
			case 'R':
			case 'r':	goto yy20;
			case 'S':
			case 's':	goto yy7;
			case 'U':
			case 'u':	goto yy8;
			case 'W':
			case 'w':	goto yy14;
			default:	goto yy29;
			}
yy2:
			++YYCURSOR;
			switch ((yych = *YYCURSOR)) {
			case 'R':
			case 'r':	goto yy218;
			case 'W':
			case 'w':	goto yy220;
			default:	goto yy32;
			}
yy3:
#line 230 "/Users/sweyrick/workspace/efind/src/scanner.re"
			{
                    token->tokType = TOKEN_WORD;
                    token->data = strndup(q, YYCURSOR - q);
                    return 0;
                }
#line 152 "/Users/sweyrick/workspace/efind/src/scanner.c"
yy4:
			++YYCURSOR;
			switch ((yych = *YYCURSOR)) {
			case '*':
			case '-':
			case '.':
			case '/':
			case '0':
			case '1':
			case '2':
			case '3':
			case '4':
			case '5':
			case '6':
			case '7':
			case '8':
			case '9':
			case '?':
			case 'A':
			case 'B':
			case 'C':
			case 'D':
			case 'E':
			case 'F':
			case 'G':
			case 'H':
			case 'I':
			case 'J':
			case 'K':
			case 'L':
			case 'M':
			case 'O':
			case 'P':
			case 'Q':
			case 'S':
			case 'T':
			case 'U':
			case 'V':
			case 'W':
			case 'X':
			case 'Y':
			case 'Z':
			case '_':
			case 'a':
			case 'b':
			case 'c':
			case 'd':
			case 'e':
			case 'f':
			case 'g':
			case 'h':
			case 'i':
			case 'j':
			case 'k':
			case 'l':
			case 'm':
			case 'o':
			case 'p':
			case 'q':
			case 's':
			case 't':
			case 'u':
			case 'v':
			case 'w':
			case 'x':
			case 'y':
			case 'z':	goto yy31;
			case 'N':
			case 'n':	goto yy214;
			case 'R':
			case 'r':	goto yy215;
			default:	goto yy5;
			}
yy5:
#line 214 "/Users/sweyrick/workspace/efind/src/scanner.re"
			{
                    token->tokType = TOKEN_CONNECTOR;
                    return 0;
                }
#line 232 "/Users/sweyrick/workspace/efind/src/scanner.c"
yy6:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'A':
			case 'a':	goto yy184;
			case 'O':
			case 'o':	goto yy185;
			default:	goto yy32;
			}
yy7:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'I':
			case 'i':	goto yy174;
			case 'O':
			case 'o':	goto yy175;
			default:	goto yy32;
			}
yy8:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'I':
			case 'i':	goto yy171;
			default:	goto yy32;
			}
yy9:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'B':
			case 'b':	goto yy148;
			case 'I':
			case 'i':	goto yy150;
			case 'R':
			case 'r':	goto yy151;
			default:	goto yy32;
			}
yy10:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'Y':
			case 'y':	goto yy143;
			default:	goto yy32;
			}
yy11:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'B':
			case 'b':	goto yy133;
			case 'I':
			case 'i':	goto yy135;
			default:	goto yy32;
			}
yy12:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'B':
			case 'b':	goto yy123;
			case 'E':
			case 'e':	goto yy125;
			default:	goto yy32;
			}
yy13:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'N':
			case 'n':	goto yy106;
			case 'S':
			case 's':	goto yy39;
			case 'W':
			case 'w':	goto yy107;
			default:	goto yy32;
			}
yy14:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'H':
			case 'h':	goto yy86;
			case 'I':
			case 'i':	goto yy87;
			case 'R':
			case 'r':	goto yy88;
			default:	goto yy32;
			}
yy15:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'I':
			case 'i':	goto yy77;
			default:	goto yy32;
			}
yy16:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'I':
			case 'i':	goto yy73;
			default:	goto yy32;
			}
yy17:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'I':
			case 'i':	goto yy69;
			default:	goto yy32;
			}
yy18:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'I':
			case 'i':	goto yy65;
			default:	goto yy32;
			}
yy19:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'M':
			case 'm':	goto yy50;
			case 'X':
			case 'x':	goto yy51;
			default:	goto yy32;
			}
yy20:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'E':
			case 'e':	goto yy42;
			default:	goto yy32;
			}
yy21:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'A':
			case 'a':	goto yy37;
			default:	goto yy32;
			}
yy22:
			++YYCURSOR;
			yych = *YYCURSOR;
			goto yy36;
yy23:
#line 219 "/Users/sweyrick/workspace/efind/src/scanner.re"
			{
                    token->tokType = TOKEN_WS;
                    return 0;
                }
#line 377 "/Users/sweyrick/workspace/efind/src/scanner.c"
yy24:
			++YYCURSOR;
			switch ((yych = *YYCURSOR)) {
			case '*':
			case '-':
			case '.':
			case '/':
			case '?':
			case 'A':
			case 'B':
			case 'C':
			case 'D':
			case 'E':
			case 'F':
			case 'G':
			case 'H':
			case 'I':
			case 'J':
			case 'K':
			case 'L':
			case 'M':
			case 'N':
			case 'O':
			case 'P':
			case 'Q':
			case 'R':
			case 'S':
			case 'T':
			case 'U':
			case 'V':
			case 'W':
			case 'X':
			case 'Y':
			case 'Z':
			case '_':
			case 'a':
			case 'b':
			case 'c':
			case 'd':
			case 'e':
			case 'f':
			case 'g':
			case 'h':
			case 'i':
			case 'j':
			case 'k':
			case 'l':
			case 'm':
			case 'n':
			case 'o':
			case 'p':
			case 'q':
			case 'r':
			case 's':
			case 't':
			case 'u':
			case 'v':
			case 'w':
			case 'x':
			case 'y':
			case 'z':	goto yy31;
			case '0':
			case '1':
			case '2':
			case '3':
			case '4':
			case '5':
			case '6':
			case '7':
			case '8':
			case '9':	goto yy33;
			default:	goto yy25;
			}
yy25:
#line 224 "/Users/sweyrick/workspace/efind/src/scanner.re"
			{
                    token->tokType = TOKEN_INT;
                    token->data = strndup(q, YYCURSOR - q);
                    return 0;
                }
#line 458 "/Users/sweyrick/workspace/efind/src/scanner.c"
yy26:
			yych = *++YYCURSOR;
			goto yy32;
yy27:
			++YYCURSOR;
#line 236 "/Users/sweyrick/workspace/efind/src/scanner.re"
			{ r = SCANNER_RETCODE_EOF; break; }
#line 466 "/Users/sweyrick/workspace/efind/src/scanner.c"
yy29:
			++YYCURSOR;
#line 238 "/Users/sweyrick/workspace/efind/src/scanner.re"
			{ r = SCANNER_RETCODE_ERR; break; }
#line 471 "/Users/sweyrick/workspace/efind/src/scanner.c"
yy31:
			++YYCURSOR;
			yych = *YYCURSOR;
yy32:
			switch (yych) {
			case '*':
			case '-':
			case '.':
			case '/':
			case '0':
			case '1':
			case '2':
			case '3':
			case '4':
			case '5':
			case '6':
			case '7':
			case '8':
			case '9':
			case '?':
			case 'A':
			case 'B':
			case 'C':
			case 'D':
			case 'E':
			case 'F':
			case 'G':
			case 'H':
			case 'I':
			case 'J':
			case 'K':
			case 'L':
			case 'M':
			case 'N':
			case 'O':
			case 'P':
			case 'Q':
			case 'R':
			case 'S':
			case 'T':
			case 'U':
			case 'V':
			case 'W':
			case 'X':
			case 'Y':
			case 'Z':
			case '_':
			case 'a':
			case 'b':
			case 'c':
			case 'd':
			case 'e':
			case 'f':
			case 'g':
			case 'h':
			case 'i':
			case 'j':
			case 'k':
			case 'l':
			case 'm':
			case 'n':
			case 'o':
			case 'p':
			case 'q':
			case 'r':
			case 's':
			case 't':
			case 'u':
			case 'v':
			case 'w':
			case 'x':
			case 'y':
			case 'z':	goto yy31;
			default:	goto yy3;
			}
yy33:
			++YYCURSOR;
			yych = *YYCURSOR;
			switch (yych) {
			case '*':
			case '-':
			case '.':
			case '/':
			case '?':
			case 'A':
			case 'B':
			case 'C':
			case 'D':
			case 'E':
			case 'F':
			case 'G':
			case 'H':
			case 'I':
			case 'J':
			case 'K':
			case 'L':
			case 'M':
			case 'N':
			case 'O':
			case 'P':
			case 'Q':
			case 'R':
			case 'S':
			case 'T':
			case 'U':
			case 'V':
			case 'W':
			case 'X':
			case 'Y':
			case 'Z':
			case '_':
			case 'a':
			case 'b':
			case 'c':
			case 'd':
			case 'e':
			case 'f':
			case 'g':
			case 'h':
			case 'i':
			case 'j':
			case 'k':
			case 'l':
			case 'm':
			case 'n':
			case 'o':
			case 'p':
			case 'q':
			case 'r':
			case 's':
			case 't':
			case 'u':
			case 'v':
			case 'w':
			case 'x':
			case 'y':
			case 'z':	goto yy31;
			case '0':
			case '1':
			case '2':
			case '3':
			case '4':
			case '5':
			case '6':
			case '7':
			case '8':
			case '9':	goto yy33;
			default:	goto yy25;
			}
yy35:
			++YYCURSOR;
			yych = *YYCURSOR;
yy36:
			switch (yych) {
			case '\t':
			case '\n':
			case '\r':
			case ' ':	goto yy35;
			default:	goto yy23;
			}
yy37:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'S':
			case 's':	goto yy39;
			case 'V':
			case 'v':	goto yy38;
			default:	goto yy32;
			}
yy38:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'I':
			case 'i':	goto yy40;
			default:	goto yy32;
			}
yy39:
			yych = *++YYCURSOR;
			switch (yych) {
			case '*':
			case '-':
			case '.':
			case '/':
			case '0':
			case '1':
			case '2':
			case '3':
			case '4':
			case '5':
			case '6':
			case '7':
			case '8':
			case '9':
			case '?':
			case 'A':
			case 'B':
			case 'C':
			case 'D':
			case 'E':
			case 'F':
			case 'G':
			case 'H':
			case 'I':
			case 'J':
			case 'K':
			case 'L':
			case 'M':
			case 'N':
			case 'O':
			case 'P':
			case 'Q':
			case 'R':
			case 'S':
			case 'T':
			case 'U':
			case 'V':
			case 'W':
			case 'X':
			case 'Y':
			case 'Z':
			case '_':
			case 'a':
			case 'b':
			case 'c':
			case 'd':
			case 'e':
			case 'f':
			case 'g':
			case 'h':
			case 'i':
			case 'j':
			case 'k':
			case 'l':
			case 'm':
			case 'n':
			case 'o':
			case 'p':
			case 'q':
			case 'r':
			case 's':
			case 't':
			case 'u':
			case 'v':
			case 'w':
			case 'x':
			case 'y':
			case 'z':	goto yy31;
			default:	goto yy5;
			}
yy40:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'N':
			case 'n':	goto yy41;
			default:	goto yy32;
			}
yy41:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'G':
			case 'g':	goto yy39;
			default:	goto yy32;
			}
yy42:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'A':
			case 'a':	goto yy43;
			default:	goto yy32;
			}
yy43:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'D':
			case 'd':	goto yy44;
			default:	goto yy32;
			}
yy44:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'A':
			case 'a':	goto yy45;
			default:	goto yy32;
			}
yy45:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'B':
			case 'b':	goto yy46;
			default:	goto yy32;
			}
yy46:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'L':
			case 'l':	goto yy47;
			default:	goto yy32;
			}
yy47:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'E':
			case 'e':	goto yy48;
			default:	goto yy32;
			}
yy48:
			++YYCURSOR;
			switch ((yych = *YYCURSOR)) {
			case '*':
			case '-':
			case '.':
			case '/':
			case '0':
			case '1':
			case '2':
			case '3':
			case '4':
			case '5':
			case '6':
			case '7':
			case '8':
			case '9':
			case '?':
			case 'A':
			case 'B':
			case 'C':
			case 'D':
			case 'E':
			case 'F':
			case 'G':
			case 'H':
			case 'I':
			case 'J':
			case 'K':
			case 'L':
			case 'M':
			case 'N':
			case 'O':
			case 'P':
			case 'Q':
			case 'R':
			case 'S':
			case 'T':
			case 'U':
			case 'V':
			case 'W':
			case 'X':
			case 'Y':
			case 'Z':
			case '_':
			case 'a':
			case 'b':
			case 'c':
			case 'd':
			case 'e':
			case 'f':
			case 'g':
			case 'h':
			case 'i':
			case 'j':
			case 'k':
			case 'l':
			case 'm':
			case 'n':
			case 'o':
			case 'p':
			case 'q':
			case 'r':
			case 's':
			case 't':
			case 'u':
			case 'v':
			case 'w':
			case 'x':
			case 'y':
			case 'z':	goto yy31;
			default:	goto yy49;
			}
yy49:
#line 202 "/Users/sweyrick/workspace/efind/src/scanner.re"
			{
                    token->tokType = TOKEN_UNARY;
                    token->opt = 4; // readable
                    return 0;
                }
#line 857 "/Users/sweyrick/workspace/efind/src/scanner.c"
yy50:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'P':
			case 'p':	goto yy61;
			default:	goto yy32;
			}
yy51:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'E':
			case 'e':	goto yy52;
			default:	goto yy32;
			}
yy52:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'C':
			case 'c':	goto yy53;
			default:	goto yy32;
			}
yy53:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'U':
			case 'u':	goto yy54;
			default:	goto yy32;
			}
yy54:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'T':
			case 't':	goto yy55;
			default:	goto yy32;
			}
yy55:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'A':
			case 'a':	goto yy56;
			default:	goto yy32;
			}
yy56:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'B':
			case 'b':	goto yy57;
			default:	goto yy32;
			}
yy57:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'L':
			case 'l':	goto yy58;
			default:	goto yy32;
			}
yy58:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'E':
			case 'e':	goto yy59;
			default:	goto yy32;
			}
yy59:
			++YYCURSOR;
			switch ((yych = *YYCURSOR)) {
			case '*':
			case '-':
			case '.':
			case '/':
			case '0':
			case '1':
			case '2':
			case '3':
			case '4':
			case '5':
			case '6':
			case '7':
			case '8':
			case '9':
			case '?':
			case 'A':
			case 'B':
			case 'C':
			case 'D':
			case 'E':
			case 'F':
			case 'G':
			case 'H':
			case 'I':
			case 'J':
			case 'K':
			case 'L':
			case 'M':
			case 'N':
			case 'O':
			case 'P':
			case 'Q':
			case 'R':
			case 'S':
			case 'T':
			case 'U':
			case 'V':
			case 'W':
			case 'X':
			case 'Y':
			case 'Z':
			case '_':
			case 'a':
			case 'b':
			case 'c':
			case 'd':
			case 'e':
			case 'f':
			case 'g':
			case 'h':
			case 'i':
			case 'j':
			case 'k':
			case 'l':
			case 'm':
			case 'n':
			case 'o':
			case 'p':
			case 'q':
			case 'r':
			case 's':
			case 't':
			case 'u':
			case 'v':
			case 'w':
			case 'x':
			case 'y':
			case 'z':	goto yy31;
			default:	goto yy60;
			}
yy60:
#line 178 "/Users/sweyrick/workspace/efind/src/scanner.re"
			{
                    token->tokType = TOKEN_UNARY;
                    token->opt = 0; // executable
                    return 0;
                }
#line 1001 "/Users/sweyrick/workspace/efind/src/scanner.c"
yy61:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'T':
			case 't':	goto yy62;
			default:	goto yy32;
			}
yy62:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'Y':
			case 'y':	goto yy63;
			default:	goto yy32;
			}
yy63:
			++YYCURSOR;
			switch ((yych = *YYCURSOR)) {
			case '*':
			case '-':
			case '.':
			case '/':
			case '0':
			case '1':
			case '2':
			case '3':
			case '4':
			case '5':
			case '6':
			case '7':
			case '8':
			case '9':
			case '?':
			case 'A':
			case 'B':
			case 'C':
			case 'D':
			case 'E':
			case 'F':
			case 'G':
			case 'H':
			case 'I':
			case 'J':
			case 'K':
			case 'L':
			case 'M':
			case 'N':
			case 'O':
			case 'P':
			case 'Q':
			case 'R':
			case 'S':
			case 'T':
			case 'U':
			case 'V':
			case 'W':
			case 'X':
			case 'Y':
			case 'Z':
			case '_':
			case 'a':
			case 'b':
			case 'c':
			case 'd':
			case 'e':
			case 'f':
			case 'g':
			case 'h':
			case 'i':
			case 'j':
			case 'k':
			case 'l':
			case 'm':
			case 'n':
			case 'o':
			case 'p':
			case 'q':
			case 'r':
			case 's':
			case 't':
			case 'u':
			case 'v':
			case 'w':
			case 'x':
			case 'y':
			case 'z':	goto yy31;
			default:	goto yy64;
			}
yy64:
#line 184 "/Users/sweyrick/workspace/efind/src/scanner.re"
			{
                    token->tokType = TOKEN_UNARY;
                    token->opt = 1; // empty
                    return 0;
                }
#line 1096 "/Users/sweyrick/workspace/efind/src/scanner.c"
yy65:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'N':
			case 'n':	goto yy66;
			default:	goto yy32;
			}
yy66:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'K':
			case 'k':	goto yy67;
			default:	goto yy32;
			}
yy67:
			++YYCURSOR;
			switch ((yych = *YYCURSOR)) {
			case '*':
			case '-':
			case '.':
			case '/':
			case '0':
			case '1':
			case '2':
			case '3':
			case '4':
			case '5':
			case '6':
			case '7':
			case '8':
			case '9':
			case '?':
			case 'A':
			case 'B':
			case 'C':
			case 'D':
			case 'E':
			case 'F':
			case 'G':
			case 'H':
			case 'I':
			case 'J':
			case 'K':
			case 'L':
			case 'M':
			case 'N':
			case 'O':
			case 'P':
			case 'Q':
			case 'R':
			case 'S':
			case 'T':
			case 'U':
			case 'V':
			case 'W':
			case 'X':
			case 'Y':
			case 'Z':
			case '_':
			case 'a':
			case 'b':
			case 'c':
			case 'd':
			case 'e':
			case 'f':
			case 'g':
			case 'h':
			case 'i':
			case 'j':
			case 'k':
			case 'l':
			case 'm':
			case 'n':
			case 'o':
			case 'p':
			case 'q':
			case 'r':
			case 's':
			case 't':
			case 'u':
			case 'v':
			case 'w':
			case 'x':
			case 'y':
			case 'z':	goto yy31;
			default:	goto yy68;
			}
yy68:
#line 166 "/Users/sweyrick/workspace/efind/src/scanner.re"
			{
                    token->tokType = TOKEN_FTYPE;
                    token->opt = 3; // link
                    return 0;
                }
#line 1191 "/Users/sweyrick/workspace/efind/src/scanner.c"
yy69:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'L':
			case 'l':	goto yy70;
			default:	goto yy32;
			}
yy70:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'E':
			case 'e':	goto yy71;
			default:	goto yy32;
			}
yy71:
			++YYCURSOR;
			switch ((yych = *YYCURSOR)) {
			case '*':
			case '-':
			case '.':
			case '/':
			case '0':
			case '1':
			case '2':
			case '3':
			case '4':
			case '5':
			case '6':
			case '7':
			case '8':
			case '9':
			case '?':
			case 'A':
			case 'B':
			case 'C':
			case 'D':
			case 'E':
			case 'F':
			case 'G':
			case 'H':
			case 'I':
			case 'J':
			case 'K':
			case 'L':
			case 'M':
			case 'N':
			case 'O':
			case 'P':
			case 'Q':
			case 'R':
			case 'S':
			case 'T':
			case 'U':
			case 'V':
			case 'W':
			case 'X':
			case 'Y':
			case 'Z':
			case '_':
			case 'a':
			case 'b':
			case 'c':
			case 'd':
			case 'e':
			case 'f':
			case 'g':
			case 'h':
			case 'i':
			case 'j':
			case 'k':
			case 'l':
			case 'm':
			case 'n':
			case 'o':
			case 'p':
			case 'q':
			case 'r':
			case 's':
			case 't':
			case 'u':
			case 'v':
			case 'w':
			case 'x':
			case 'y':
			case 'z':	goto yy31;
			default:	goto yy72;
			}
yy72:
#line 160 "/Users/sweyrick/workspace/efind/src/scanner.re"
			{
                    token->tokType = TOKEN_FTYPE;
                    token->opt = 2; // file
                    return 0;
                }
#line 1286 "/Users/sweyrick/workspace/efind/src/scanner.c"
yy73:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'P':
			case 'p':	goto yy74;
			default:	goto yy32;
			}
yy74:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'E':
			case 'e':	goto yy75;
			default:	goto yy32;
			}
yy75:
			++YYCURSOR;
			switch ((yych = *YYCURSOR)) {
			case '*':
			case '-':
			case '.':
			case '/':
			case '0':
			case '1':
			case '2':
			case '3':
			case '4':
			case '5':
			case '6':
			case '7':
			case '8':
			case '9':
			case '?':
			case 'A':
			case 'B':
			case 'C':
			case 'D':
			case 'E':
			case 'F':
			case 'G':
			case 'H':
			case 'I':
			case 'J':
			case 'K':
			case 'L':
			case 'M':
			case 'N':
			case 'O':
			case 'P':
			case 'Q':
			case 'R':
			case 'S':
			case 'T':
			case 'U':
			case 'V':
			case 'W':
			case 'X':
			case 'Y':
			case 'Z':
			case '_':
			case 'a':
			case 'b':
			case 'c':
			case 'd':
			case 'e':
			case 'f':
			case 'g':
			case 'h':
			case 'i':
			case 'j':
			case 'k':
			case 'l':
			case 'm':
			case 'n':
			case 'o':
			case 'p':
			case 'q':
			case 'r':
			case 's':
			case 't':
			case 'u':
			case 'v':
			case 'w':
			case 'x':
			case 'y':
			case 'z':	goto yy31;
			default:	goto yy76;
			}
yy76:
#line 154 "/Users/sweyrick/workspace/efind/src/scanner.re"
			{
                    token->tokType = TOKEN_FTYPE;
                    token->opt = 1; // pipe
                    return 0;
                }
#line 1381 "/Users/sweyrick/workspace/efind/src/scanner.c"
yy77:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'R':
			case 'r':	goto yy78;
			default:	goto yy32;
			}
yy78:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'E':
			case 'e':	goto yy79;
			default:	goto yy32;
			}
yy79:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'C':
			case 'c':	goto yy80;
			default:	goto yy32;
			}
yy80:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'T':
			case 't':	goto yy81;
			default:	goto yy32;
			}
yy81:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'O':
			case 'o':	goto yy82;
			default:	goto yy32;
			}
yy82:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'R':
			case 'r':	goto yy83;
			default:	goto yy32;
			}
yy83:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'Y':
			case 'y':	goto yy84;
			default:	goto yy32;
			}
yy84:
			++YYCURSOR;
			switch ((yych = *YYCURSOR)) {
			case '*':
			case '-':
			case '.':
			case '/':
			case '0':
			case '1':
			case '2':
			case '3':
			case '4':
			case '5':
			case '6':
			case '7':
			case '8':
			case '9':
			case '?':
			case 'A':
			case 'B':
			case 'C':
			case 'D':
			case 'E':
			case 'F':
			case 'G':
			case 'H':
			case 'I':
			case 'J':
			case 'K':
			case 'L':
			case 'M':
			case 'N':
			case 'O':
			case 'P':
			case 'Q':
			case 'R':
			case 'S':
			case 'T':
			case 'U':
			case 'V':
			case 'W':
			case 'X':
			case 'Y':
			case 'Z':
			case '_':
			case 'a':
			case 'b':
			case 'c':
			case 'd':
			case 'e':
			case 'f':
			case 'g':
			case 'h':
			case 'i':
			case 'j':
			case 'k':
			case 'l':
			case 'm':
			case 'n':
			case 'o':
			case 'p':
			case 'q':
			case 'r':
			case 's':
			case 't':
			case 'u':
			case 'v':
			case 'w':
			case 'x':
			case 'y':
			case 'z':	goto yy31;
			default:	goto yy85;
			}
yy85:
#line 148 "/Users/sweyrick/workspace/efind/src/scanner.re"
			{
                    token->tokType = TOKEN_FTYPE;
                    token->opt = 0; // directory
                    return 0;
                }
#line 1511 "/Users/sweyrick/workspace/efind/src/scanner.c"
yy86:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'O':
			case 'o':	goto yy97;
			default:	goto yy32;
			}
yy87:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'T':
			case 't':	goto yy96;
			default:	goto yy32;
			}
yy88:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'I':
			case 'i':	goto yy89;
			default:	goto yy32;
			}
yy89:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'T':
			case 't':	goto yy90;
			default:	goto yy32;
			}
yy90:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'A':
			case 'a':	goto yy91;
			default:	goto yy32;
			}
yy91:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'B':
			case 'b':	goto yy92;
			default:	goto yy32;
			}
yy92:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'L':
			case 'l':	goto yy93;
			default:	goto yy32;
			}
yy93:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'E':
			case 'e':	goto yy94;
			default:	goto yy32;
			}
yy94:
			++YYCURSOR;
			switch ((yych = *YYCURSOR)) {
			case '*':
			case '-':
			case '.':
			case '/':
			case '0':
			case '1':
			case '2':
			case '3':
			case '4':
			case '5':
			case '6':
			case '7':
			case '8':
			case '9':
			case '?':
			case 'A':
			case 'B':
			case 'C':
			case 'D':
			case 'E':
			case 'F':
			case 'G':
			case 'H':
			case 'I':
			case 'J':
			case 'K':
			case 'L':
			case 'M':
			case 'N':
			case 'O':
			case 'P':
			case 'Q':
			case 'R':
			case 'S':
			case 'T':
			case 'U':
			case 'V':
			case 'W':
			case 'X':
			case 'Y':
			case 'Z':
			case '_':
			case 'a':
			case 'b':
			case 'c':
			case 'd':
			case 'e':
			case 'f':
			case 'g':
			case 'h':
			case 'i':
			case 'j':
			case 'k':
			case 'l':
			case 'm':
			case 'n':
			case 'o':
			case 'p':
			case 'q':
			case 'r':
			case 's':
			case 't':
			case 'u':
			case 'v':
			case 'w':
			case 'x':
			case 'y':
			case 'z':	goto yy31;
			default:	goto yy95;
			}
yy95:
#line 208 "/Users/sweyrick/workspace/efind/src/scanner.re"
			{
                    token->tokType = TOKEN_UNARY;
                    token->opt = 5; // writable
                    return 0;
                }
#line 1648 "/Users/sweyrick/workspace/efind/src/scanner.c"
yy96:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'H':
			case 'h':	goto yy39;
			default:	goto yy32;
			}
yy97:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'L':
			case 'l':	goto yy98;
			default:	goto yy32;
			}
yy98:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'E':
			case 'e':	goto yy99;
			default:	goto yy32;
			}
yy99:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'N':
			case 'n':	goto yy100;
			default:	goto yy32;
			}
yy100:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'A':
			case 'a':	goto yy101;
			default:	goto yy32;
			}
yy101:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'M':
			case 'm':	goto yy102;
			default:	goto yy32;
			}
yy102:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'E':
			case 'e':	goto yy103;
			default:	goto yy32;
			}
yy103:
			++YYCURSOR;
			yych = *YYCURSOR;
			switch (yych) {
			case '*':
			case '-':
			case '.':
			case '/':
			case '0':
			case '1':
			case '2':
			case '3':
			case '4':
			case '5':
			case '6':
			case '7':
			case '8':
			case '9':
			case '?':
			case 'A':
			case 'B':
			case 'C':
			case 'E':
			case 'F':
			case 'G':
			case 'H':
			case 'I':
			case 'J':
			case 'K':
			case 'L':
			case 'M':
			case 'N':
			case 'O':
			case 'P':
			case 'Q':
			case 'R':
			case 'S':
			case 'T':
			case 'U':
			case 'V':
			case 'W':
			case 'X':
			case 'Y':
			case 'Z':
			case '_':
			case 'a':
			case 'b':
			case 'c':
			case 'e':
			case 'f':
			case 'g':
			case 'h':
			case 'i':
			case 'j':
			case 'k':
			case 'l':
			case 'm':
			case 'n':
			case 'o':
			case 'p':
			case 'q':
			case 'r':
			case 's':
			case 't':
			case 'u':
			case 'v':
			case 'w':
			case 'x':
			case 'y':
			case 'z':	goto yy31;
			case 'D':
			case 'd':	goto yy103;
			default:	goto yy105;
			}
yy105:
#line 136 "/Users/sweyrick/workspace/efind/src/scanner.re"
			{
                    token->tokType = TOKEN_NAMED;
                    token->opt = 2; // wholename
                    return 0;
                }
#line 1779 "/Users/sweyrick/workspace/efind/src/scanner.c"
yy106:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'A':
			case 'a':	goto yy118;
			default:	goto yy32;
			}
yy107:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'H':
			case 'h':	goto yy108;
			default:	goto yy32;
			}
yy108:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'O':
			case 'o':	goto yy109;
			default:	goto yy32;
			}
yy109:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'L':
			case 'l':	goto yy110;
			default:	goto yy32;
			}
yy110:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'E':
			case 'e':	goto yy111;
			default:	goto yy32;
			}
yy111:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'N':
			case 'n':	goto yy112;
			default:	goto yy32;
			}
yy112:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'A':
			case 'a':	goto yy113;
			default:	goto yy32;
			}
yy113:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'M':
			case 'm':	goto yy114;
			default:	goto yy32;
			}
yy114:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'E':
			case 'e':	goto yy115;
			default:	goto yy32;
			}
yy115:
			++YYCURSOR;
			yych = *YYCURSOR;
			switch (yych) {
			case '*':
			case '-':
			case '.':
			case '/':
			case '0':
			case '1':
			case '2':
			case '3':
			case '4':
			case '5':
			case '6':
			case '7':
			case '8':
			case '9':
			case '?':
			case 'A':
			case 'B':
			case 'C':
			case 'E':
			case 'F':
			case 'G':
			case 'H':
			case 'I':
			case 'J':
			case 'K':
			case 'L':
			case 'M':
			case 'N':
			case 'O':
			case 'P':
			case 'Q':
			case 'R':
			case 'S':
			case 'T':
			case 'U':
			case 'V':
			case 'W':
			case 'X':
			case 'Y':
			case 'Z':
			case '_':
			case 'a':
			case 'b':
			case 'c':
			case 'e':
			case 'f':
			case 'g':
			case 'h':
			case 'i':
			case 'j':
			case 'k':
			case 'l':
			case 'm':
			case 'n':
			case 'o':
			case 'p':
			case 'q':
			case 'r':
			case 's':
			case 't':
			case 'u':
			case 'v':
			case 'w':
			case 'x':
			case 'y':
			case 'z':	goto yy31;
			case 'D':
			case 'd':	goto yy115;
			default:	goto yy117;
			}
yy117:
#line 142 "/Users/sweyrick/workspace/efind/src/scanner.re"
			{
                    token->tokType = TOKEN_NAMED;
                    token->opt = 3; // iwholename
                    return 0;
                }
#line 1924 "/Users/sweyrick/workspace/efind/src/scanner.c"
yy118:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'M':
			case 'm':	goto yy119;
			default:	goto yy32;
			}
yy119:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'E':
			case 'e':	goto yy120;
			default:	goto yy32;
			}
yy120:
			++YYCURSOR;
			yych = *YYCURSOR;
			switch (yych) {
			case '*':
			case '-':
			case '.':
			case '/':
			case '0':
			case '1':
			case '2':
			case '3':
			case '4':
			case '5':
			case '6':
			case '7':
			case '8':
			case '9':
			case '?':
			case 'A':
			case 'B':
			case 'C':
			case 'E':
			case 'F':
			case 'G':
			case 'H':
			case 'I':
			case 'J':
			case 'K':
			case 'L':
			case 'M':
			case 'N':
			case 'O':
			case 'P':
			case 'Q':
			case 'R':
			case 'S':
			case 'T':
			case 'U':
			case 'V':
			case 'W':
			case 'X':
			case 'Y':
			case 'Z':
			case '_':
			case 'a':
			case 'b':
			case 'c':
			case 'e':
			case 'f':
			case 'g':
			case 'h':
			case 'i':
			case 'j':
			case 'k':
			case 'l':
			case 'm':
			case 'n':
			case 'o':
			case 'p':
			case 'q':
			case 'r':
			case 's':
			case 't':
			case 'u':
			case 'v':
			case 'w':
			case 'x':
			case 'y':
			case 'z':	goto yy31;
			case 'D':
			case 'd':	goto yy120;
			default:	goto yy122;
			}
yy122:
#line 130 "/Users/sweyrick/workspace/efind/src/scanner.re"
			{
                    token->tokType = TOKEN_NAMED;
                    token->opt = 1; // iname
                    return 0;
                }
#line 2020 "/Users/sweyrick/workspace/efind/src/scanner.c"
yy123:
			++YYCURSOR;
			switch ((yych = *YYCURSOR)) {
			case '*':
			case '-':
			case '.':
			case '/':
			case '0':
			case '1':
			case '2':
			case '3':
			case '4':
			case '5':
			case '6':
			case '7':
			case '8':
			case '9':
			case '?':
			case 'A':
			case 'B':
			case 'C':
			case 'D':
			case 'E':
			case 'F':
			case 'G':
			case 'H':
			case 'I':
			case 'J':
			case 'K':
			case 'L':
			case 'M':
			case 'N':
			case 'O':
			case 'P':
			case 'Q':
			case 'R':
			case 'S':
			case 'T':
			case 'U':
			case 'V':
			case 'W':
			case 'X':
			case 'Y':
			case 'Z':
			case '_':
			case 'a':
			case 'b':
			case 'c':
			case 'd':
			case 'e':
			case 'f':
			case 'g':
			case 'h':
			case 'i':
			case 'j':
			case 'k':
			case 'l':
			case 'm':
			case 'n':
			case 'o':
			case 'p':
			case 'q':
			case 'r':
			case 's':
			case 't':
			case 'u':
			case 'v':
			case 'w':
			case 'x':
			case 'y':
			case 'z':	goto yy31;
			default:	goto yy124;
			}
yy124:
#line 102 "/Users/sweyrick/workspace/efind/src/scanner.re"
			{
                    token->tokType = TOKEN_SIZEQUAL;
                    token->opt = 'M';
                    return 0;
                }
#line 2101 "/Users/sweyrick/workspace/efind/src/scanner.c"
yy125:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'G':
			case 'g':	goto yy126;
			default:	goto yy32;
			}
yy126:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'A':
			case 'a':	goto yy127;
			default:	goto yy32;
			}
yy127:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'B':
			case 'b':	goto yy128;
			default:	goto yy32;
			}
yy128:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'Y':
			case 'y':	goto yy129;
			default:	goto yy32;
			}
yy129:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'T':
			case 't':	goto yy130;
			default:	goto yy32;
			}
yy130:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'E':
			case 'e':	goto yy131;
			default:	goto yy32;
			}
yy131:
			++YYCURSOR;
			yych = *YYCURSOR;
			switch (yych) {
			case '*':
			case '-':
			case '.':
			case '/':
			case '0':
			case '1':
			case '2':
			case '3':
			case '4':
			case '5':
			case '6':
			case '7':
			case '8':
			case '9':
			case '?':
			case 'A':
			case 'B':
			case 'C':
			case 'D':
			case 'E':
			case 'F':
			case 'G':
			case 'H':
			case 'I':
			case 'J':
			case 'K':
			case 'L':
			case 'M':
			case 'N':
			case 'O':
			case 'P':
			case 'Q':
			case 'R':
			case 'T':
			case 'U':
			case 'V':
			case 'W':
			case 'X':
			case 'Y':
			case 'Z':
			case '_':
			case 'a':
			case 'b':
			case 'c':
			case 'd':
			case 'e':
			case 'f':
			case 'g':
			case 'h':
			case 'i':
			case 'j':
			case 'k':
			case 'l':
			case 'm':
			case 'n':
			case 'o':
			case 'p':
			case 'q':
			case 'r':
			case 't':
			case 'u':
			case 'v':
			case 'w':
			case 'x':
			case 'y':
			case 'z':	goto yy31;
			case 'S':
			case 's':	goto yy131;
			default:	goto yy124;
			}
yy133:
			++YYCURSOR;
			switch ((yych = *YYCURSOR)) {
			case '*':
			case '-':
			case '.':
			case '/':
			case '0':
			case '1':
			case '2':
			case '3':
			case '4':
			case '5':
			case '6':
			case '7':
			case '8':
			case '9':
			case '?':
			case 'A':
			case 'B':
			case 'C':
			case 'D':
			case 'E':
			case 'F':
			case 'G':
			case 'H':
			case 'I':
			case 'J':
			case 'K':
			case 'L':
			case 'M':
			case 'N':
			case 'O':
			case 'P':
			case 'Q':
			case 'R':
			case 'S':
			case 'T':
			case 'U':
			case 'V':
			case 'W':
			case 'X':
			case 'Y':
			case 'Z':
			case '_':
			case 'a':
			case 'b':
			case 'c':
			case 'd':
			case 'e':
			case 'f':
			case 'g':
			case 'h':
			case 'i':
			case 'j':
			case 'k':
			case 'l':
			case 'm':
			case 'n':
			case 'o':
			case 'p':
			case 'q':
			case 'r':
			case 's':
			case 't':
			case 'u':
			case 'v':
			case 'w':
			case 'x':
			case 'y':
			case 'z':	goto yy31;
			default:	goto yy134;
			}
yy134:
#line 96 "/Users/sweyrick/workspace/efind/src/scanner.re"
			{
                    token->tokType = TOKEN_SIZEQUAL;
                    token->opt = 'k';
                    return 0;
                }
#line 2298 "/Users/sweyrick/workspace/efind/src/scanner.c"
yy135:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'L':
			case 'l':	goto yy136;
			default:	goto yy32;
			}
yy136:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'O':
			case 'o':	goto yy137;
			default:	goto yy32;
			}
yy137:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'B':
			case 'b':	goto yy138;
			default:	goto yy32;
			}
yy138:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'Y':
			case 'y':	goto yy139;
			default:	goto yy32;
			}
yy139:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'T':
			case 't':	goto yy140;
			default:	goto yy32;
			}
yy140:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'E':
			case 'e':	goto yy141;
			default:	goto yy32;
			}
yy141:
			++YYCURSOR;
			yych = *YYCURSOR;
			switch (yych) {
			case '*':
			case '-':
			case '.':
			case '/':
			case '0':
			case '1':
			case '2':
			case '3':
			case '4':
			case '5':
			case '6':
			case '7':
			case '8':
			case '9':
			case '?':
			case 'A':
			case 'B':
			case 'C':
			case 'D':
			case 'E':
			case 'F':
			case 'G':
			case 'H':
			case 'I':
			case 'J':
			case 'K':
			case 'L':
			case 'M':
			case 'N':
			case 'O':
			case 'P':
			case 'Q':
			case 'R':
			case 'T':
			case 'U':
			case 'V':
			case 'W':
			case 'X':
			case 'Y':
			case 'Z':
			case '_':
			case 'a':
			case 'b':
			case 'c':
			case 'd':
			case 'e':
			case 'f':
			case 'g':
			case 'h':
			case 'i':
			case 'j':
			case 'k':
			case 'l':
			case 'm':
			case 'n':
			case 'o':
			case 'p':
			case 'q':
			case 'r':
			case 't':
			case 'u':
			case 'v':
			case 'w':
			case 'x':
			case 'y':
			case 'z':	goto yy31;
			case 'S':
			case 's':	goto yy141;
			default:	goto yy134;
			}
yy143:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'T':
			case 't':	goto yy144;
			default:	goto yy32;
			}
yy144:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'E':
			case 'e':	goto yy145;
			default:	goto yy32;
			}
yy145:
			++YYCURSOR;
			yych = *YYCURSOR;
			switch (yych) {
			case '*':
			case '-':
			case '.':
			case '/':
			case '0':
			case '1':
			case '2':
			case '3':
			case '4':
			case '5':
			case '6':
			case '7':
			case '8':
			case '9':
			case '?':
			case 'A':
			case 'B':
			case 'C':
			case 'D':
			case 'E':
			case 'F':
			case 'G':
			case 'H':
			case 'I':
			case 'J':
			case 'K':
			case 'L':
			case 'M':
			case 'N':
			case 'O':
			case 'P':
			case 'Q':
			case 'R':
			case 'T':
			case 'U':
			case 'V':
			case 'W':
			case 'X':
			case 'Y':
			case 'Z':
			case '_':
			case 'a':
			case 'b':
			case 'c':
			case 'd':
			case 'e':
			case 'f':
			case 'g':
			case 'h':
			case 'i':
			case 'j':
			case 'k':
			case 'l':
			case 'm':
			case 'n':
			case 'o':
			case 'p':
			case 'q':
			case 'r':
			case 't':
			case 'u':
			case 'v':
			case 'w':
			case 'x':
			case 'y':
			case 'z':	goto yy31;
			case 'S':
			case 's':	goto yy145;
			default:	goto yy147;
			}
yy147:
#line 90 "/Users/sweyrick/workspace/efind/src/scanner.re"
			{
                    token->tokType = TOKEN_SIZEQUAL;
                    token->opt = 'c';
                    return 0;
                }
#line 2510 "/Users/sweyrick/workspace/efind/src/scanner.c"
yy148:
			++YYCURSOR;
			switch ((yych = *YYCURSOR)) {
			case '*':
			case '-':
			case '.':
			case '/':
			case '0':
			case '1':
			case '2':
			case '3':
			case '4':
			case '5':
			case '6':
			case '7':
			case '8':
			case '9':
			case '?':
			case 'A':
			case 'B':
			case 'C':
			case 'D':
			case 'E':
			case 'F':
			case 'G':
			case 'H':
			case 'I':
			case 'J':
			case 'K':
			case 'L':
			case 'M':
			case 'N':
			case 'O':
			case 'P':
			case 'Q':
			case 'R':
			case 'S':
			case 'T':
			case 'U':
			case 'V':
			case 'W':
			case 'X':
			case 'Y':
			case 'Z':
			case '_':
			case 'a':
			case 'b':
			case 'c':
			case 'd':
			case 'e':
			case 'f':
			case 'g':
			case 'h':
			case 'i':
			case 'j':
			case 'k':
			case 'l':
			case 'm':
			case 'n':
			case 'o':
			case 'p':
			case 'q':
			case 'r':
			case 's':
			case 't':
			case 'u':
			case 'v':
			case 'w':
			case 'x':
			case 'y':
			case 'z':	goto yy31;
			default:	goto yy149;
			}
yy149:
#line 108 "/Users/sweyrick/workspace/efind/src/scanner.re"
			{
                    token->tokType = TOKEN_SIZEQUAL;
                    token->opt = 'G';
                    return 0;
                }
#line 2591 "/Users/sweyrick/workspace/efind/src/scanner.c"
yy150:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'D':
			case 'd':	goto yy162;
			case 'G':
			case 'g':	goto yy164;
			default:	goto yy32;
			}
yy151:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'O':
			case 'o':	goto yy152;
			default:	goto yy32;
			}
yy152:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'U':
			case 'u':	goto yy153;
			default:	goto yy32;
			}
yy153:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'P':
			case 'p':	goto yy154;
			default:	goto yy32;
			}
yy154:
			++YYCURSOR;
			switch ((yych = *YYCURSOR)) {
			case '*':
			case '-':
			case '.':
			case '/':
			case '0':
			case '1':
			case '2':
			case '3':
			case '4':
			case '5':
			case '6':
			case '7':
			case '8':
			case '9':
			case '?':
			case 'A':
			case 'B':
			case 'C':
			case 'D':
			case 'F':
			case 'G':
			case 'H':
			case 'I':
			case 'J':
			case 'K':
			case 'L':
			case 'M':
			case 'N':
			case 'O':
			case 'P':
			case 'Q':
			case 'R':
			case 'S':
			case 'T':
			case 'U':
			case 'V':
			case 'W':
			case 'X':
			case 'Y':
			case 'Z':
			case '_':
			case 'a':
			case 'b':
			case 'c':
			case 'd':
			case 'f':
			case 'g':
			case 'h':
			case 'i':
			case 'j':
			case 'k':
			case 'l':
			case 'm':
			case 'n':
			case 'o':
			case 'p':
			case 'q':
			case 'r':
			case 's':
			case 't':
			case 'u':
			case 'v':
			case 'w':
			case 'x':
			case 'y':
			case 'z':	goto yy31;
			case 'E':
			case 'e':	goto yy156;
			default:	goto yy155;
			}
yy155:
#line 119 "/Users/sweyrick/workspace/efind/src/scanner.re"
			{
                    token->tokType = TOKEN_GROUPEDBY;
                    return 0;
                }
#line 2701 "/Users/sweyrick/workspace/efind/src/scanner.c"
yy156:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'D':
			case 'd':	goto yy157;
			default:	goto yy32;
			}
yy157:
			yych = *(YYMARKER = ++YYCURSOR);
			switch (yych) {
			case ' ':	goto yy158;
			default:	goto yy32;
			}
yy158:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'B':
			case 'b':	goto yy160;
			default:	goto yy159;
			}
yy159:
			YYCURSOR = YYMARKER;
			goto yy3;
yy160:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'Y':
			case 'y':	goto yy161;
			default:	goto yy159;
			}
yy161:
			yych = *++YYCURSOR;
			goto yy155;
yy162:
			++YYCURSOR;
			switch ((yych = *YYCURSOR)) {
			case '*':
			case '-':
			case '.':
			case '/':
			case '0':
			case '1':
			case '2':
			case '3':
			case '4':
			case '5':
			case '6':
			case '7':
			case '8':
			case '9':
			case '?':
			case 'A':
			case 'B':
			case 'C':
			case 'D':
			case 'E':
			case 'F':
			case 'G':
			case 'H':
			case 'I':
			case 'J':
			case 'K':
			case 'L':
			case 'M':
			case 'N':
			case 'O':
			case 'P':
			case 'Q':
			case 'R':
			case 'S':
			case 'T':
			case 'U':
			case 'V':
			case 'W':
			case 'X':
			case 'Y':
			case 'Z':
			case '_':
			case 'a':
			case 'b':
			case 'c':
			case 'd':
			case 'e':
			case 'f':
			case 'g':
			case 'h':
			case 'i':
			case 'j':
			case 'k':
			case 'l':
			case 'm':
			case 'n':
			case 'o':
			case 'p':
			case 'q':
			case 'r':
			case 's':
			case 't':
			case 'u':
			case 'v':
			case 'w':
			case 'x':
			case 'y':
			case 'z':	goto yy31;
			default:	goto yy163;
			}
yy163:
#line 85 "/Users/sweyrick/workspace/efind/src/scanner.re"
			{
                    token->tokType = TOKEN_GID;
                    return 0;
                }
#line 2814 "/Users/sweyrick/workspace/efind/src/scanner.c"
yy164:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'A':
			case 'a':	goto yy165;
			default:	goto yy32;
			}
yy165:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'B':
			case 'b':	goto yy166;
			default:	goto yy32;
			}
yy166:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'Y':
			case 'y':	goto yy167;
			default:	goto yy32;
			}
yy167:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'T':
			case 't':	goto yy168;
			default:	goto yy32;
			}
yy168:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'E':
			case 'e':	goto yy169;
			default:	goto yy32;
			}
yy169:
			++YYCURSOR;
			yych = *YYCURSOR;
			switch (yych) {
			case '*':
			case '-':
			case '.':
			case '/':
			case '0':
			case '1':
			case '2':
			case '3':
			case '4':
			case '5':
			case '6':
			case '7':
			case '8':
			case '9':
			case '?':
			case 'A':
			case 'B':
			case 'C':
			case 'D':
			case 'E':
			case 'F':
			case 'G':
			case 'H':
			case 'I':
			case 'J':
			case 'K':
			case 'L':
			case 'M':
			case 'N':
			case 'O':
			case 'P':
			case 'Q':
			case 'R':
			case 'T':
			case 'U':
			case 'V':
			case 'W':
			case 'X':
			case 'Y':
			case 'Z':
			case '_':
			case 'a':
			case 'b':
			case 'c':
			case 'd':
			case 'e':
			case 'f':
			case 'g':
			case 'h':
			case 'i':
			case 'j':
			case 'k':
			case 'l':
			case 'm':
			case 'n':
			case 'o':
			case 'p':
			case 'q':
			case 'r':
			case 't':
			case 'u':
			case 'v':
			case 'w':
			case 'x':
			case 'y':
			case 'z':	goto yy31;
			case 'S':
			case 's':	goto yy169;
			default:	goto yy149;
			}
yy171:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'D':
			case 'd':	goto yy172;
			default:	goto yy32;
			}
yy172:
			++YYCURSOR;
			switch ((yych = *YYCURSOR)) {
			case '*':
			case '-':
			case '.':
			case '/':
			case '0':
			case '1':
			case '2':
			case '3':
			case '4':
			case '5':
			case '6':
			case '7':
			case '8':
			case '9':
			case '?':
			case 'A':
			case 'B':
			case 'C':
			case 'D':
			case 'E':
			case 'F':
			case 'G':
			case 'H':
			case 'I':
			case 'J':
			case 'K':
			case 'L':
			case 'M':
			case 'N':
			case 'O':
			case 'P':
			case 'Q':
			case 'R':
			case 'S':
			case 'T':
			case 'U':
			case 'V':
			case 'W':
			case 'X':
			case 'Y':
			case 'Z':
			case '_':
			case 'a':
			case 'b':
			case 'c':
			case 'd':
			case 'e':
			case 'f':
			case 'g':
			case 'h':
			case 'i':
			case 'j':
			case 'k':
			case 'l':
			case 'm':
			case 'n':
			case 'o':
			case 'p':
			case 'q':
			case 'r':
			case 's':
			case 't':
			case 'u':
			case 'v':
			case 'w':
			case 'x':
			case 'y':
			case 'z':	goto yy31;
			default:	goto yy173;
			}
yy173:
#line 80 "/Users/sweyrick/workspace/efind/src/scanner.re"
			{
                    token->tokType = TOKEN_UID;
                    return 0;
                }
#line 3010 "/Users/sweyrick/workspace/efind/src/scanner.c"
yy174:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'Z':
			case 'z':	goto yy181;
			default:	goto yy32;
			}
yy175:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'C':
			case 'c':	goto yy176;
			default:	goto yy32;
			}
yy176:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'K':
			case 'k':	goto yy177;
			default:	goto yy32;
			}
yy177:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'E':
			case 'e':	goto yy178;
			default:	goto yy32;
			}
yy178:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'T':
			case 't':	goto yy179;
			default:	goto yy32;
			}
yy179:
			++YYCURSOR;
			switch ((yych = *YYCURSOR)) {
			case '*':
			case '-':
			case '.':
			case '/':
			case '0':
			case '1':
			case '2':
			case '3':
			case '4':
			case '5':
			case '6':
			case '7':
			case '8':
			case '9':
			case '?':
			case 'A':
			case 'B':
			case 'C':
			case 'D':
			case 'E':
			case 'F':
			case 'G':
			case 'H':
			case 'I':
			case 'J':
			case 'K':
			case 'L':
			case 'M':
			case 'N':
			case 'O':
			case 'P':
			case 'Q':
			case 'R':
			case 'S':
			case 'T':
			case 'U':
			case 'V':
			case 'W':
			case 'X':
			case 'Y':
			case 'Z':
			case '_':
			case 'a':
			case 'b':
			case 'c':
			case 'd':
			case 'e':
			case 'f':
			case 'g':
			case 'h':
			case 'i':
			case 'j':
			case 'k':
			case 'l':
			case 'm':
			case 'n':
			case 'o':
			case 'p':
			case 'q':
			case 'r':
			case 's':
			case 't':
			case 'u':
			case 'v':
			case 'w':
			case 'x':
			case 'y':
			case 'z':	goto yy31;
			default:	goto yy180;
			}
yy180:
#line 172 "/Users/sweyrick/workspace/efind/src/scanner.re"
			{
                    token->tokType = TOKEN_FTYPE;
                    token->opt = 4; // socket
                    return 0;
                }
#line 3126 "/Users/sweyrick/workspace/efind/src/scanner.c"
yy181:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'E':
			case 'e':	goto yy182;
			default:	goto yy32;
			}
yy182:
			++YYCURSOR;
			switch ((yych = *YYCURSOR)) {
			case '*':
			case '-':
			case '.':
			case '/':
			case '0':
			case '1':
			case '2':
			case '3':
			case '4':
			case '5':
			case '6':
			case '7':
			case '8':
			case '9':
			case '?':
			case 'A':
			case 'B':
			case 'C':
			case 'D':
			case 'E':
			case 'F':
			case 'G':
			case 'H':
			case 'I':
			case 'J':
			case 'K':
			case 'L':
			case 'M':
			case 'N':
			case 'O':
			case 'P':
			case 'Q':
			case 'R':
			case 'S':
			case 'T':
			case 'U':
			case 'V':
			case 'W':
			case 'X':
			case 'Y':
			case 'Z':
			case '_':
			case 'a':
			case 'b':
			case 'c':
			case 'd':
			case 'e':
			case 'f':
			case 'g':
			case 'h':
			case 'i':
			case 'j':
			case 'k':
			case 'l':
			case 'm':
			case 'n':
			case 'o':
			case 'p':
			case 'q':
			case 'r':
			case 's':
			case 't':
			case 'u':
			case 'v':
			case 'w':
			case 'x':
			case 'y':
			case 'z':	goto yy31;
			default:	goto yy183;
			}
yy183:
#line 75 "/Users/sweyrick/workspace/efind/src/scanner.re"
			{
                    token->tokType = TOKEN_SIZE;
                    return 0;
                }
#line 3213 "/Users/sweyrick/workspace/efind/src/scanner.c"
yy184:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'M':
			case 'm':	goto yy210;
			default:	goto yy32;
			}
yy185:
			yych = *(YYMARKER = ++YYCURSOR);
			switch (yych) {
			case '\t':
			case '\n':
			case '\r':
			case ' ':	goto yy188;
			case '*':
			case '-':
			case '.':
			case '/':
			case '0':
			case '1':
			case '2':
			case '3':
			case '4':
			case '5':
			case '6':
			case '7':
			case '8':
			case '9':
			case '?':
			case 'A':
			case 'B':
			case 'C':
			case 'D':
			case 'E':
			case 'F':
			case 'H':
			case 'I':
			case 'J':
			case 'K':
			case 'L':
			case 'M':
			case 'N':
			case 'O':
			case 'P':
			case 'Q':
			case 'R':
			case 'S':
			case 'V':
			case 'W':
			case 'X':
			case 'Y':
			case 'Z':
			case '_':
			case 'a':
			case 'b':
			case 'c':
			case 'd':
			case 'e':
			case 'f':
			case 'h':
			case 'i':
			case 'j':
			case 'k':
			case 'l':
			case 'm':
			case 'n':
			case 'o':
			case 'p':
			case 'q':
			case 'r':
			case 's':
			case 'v':
			case 'w':
			case 'x':
			case 'y':
			case 'z':	goto yy31;
			case 'G':
			case 'g':	goto yy190;
			case 'T':
			case 't':	goto yy186;
			case 'U':
			case 'u':	goto yy191;
			default:	goto yy3;
			}
yy186:
			++YYCURSOR;
			switch ((yych = *YYCURSOR)) {
			case '*':
			case '-':
			case '.':
			case '/':
			case '0':
			case '1':
			case '2':
			case '3':
			case '4':
			case '5':
			case '6':
			case '7':
			case '8':
			case '9':
			case '?':
			case 'A':
			case 'B':
			case 'C':
			case 'D':
			case 'E':
			case 'F':
			case 'G':
			case 'H':
			case 'I':
			case 'J':
			case 'K':
			case 'L':
			case 'M':
			case 'N':
			case 'O':
			case 'P':
			case 'Q':
			case 'R':
			case 'S':
			case 'T':
			case 'U':
			case 'V':
			case 'W':
			case 'X':
			case 'Y':
			case 'Z':
			case '_':
			case 'a':
			case 'b':
			case 'c':
			case 'd':
			case 'e':
			case 'f':
			case 'g':
			case 'h':
			case 'i':
			case 'j':
			case 'k':
			case 'l':
			case 'm':
			case 'n':
			case 'o':
			case 'p':
			case 'q':
			case 'r':
			case 's':
			case 't':
			case 'u':
			case 'v':
			case 'w':
			case 'x':
			case 'y':
			case 'z':	goto yy31;
			default:	goto yy187;
			}
yy187:
#line 70 "/Users/sweyrick/workspace/efind/src/scanner.re"
			{
                    token->tokType = TOKEN_NOT;
                    return 0;
                }
#line 3377 "/Users/sweyrick/workspace/efind/src/scanner.c"
yy188:
			++YYCURSOR;
			yych = *YYCURSOR;
			switch (yych) {
			case '\t':
			case '\n':
			case '\r':
			case ' ':	goto yy188;
			case 'G':
			case 'g':	goto yy202;
			case 'U':
			case 'u':	goto yy201;
			default:	goto yy159;
			}
yy190:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'R':
			case 'r':	goto yy196;
			default:	goto yy32;
			}
yy191:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'S':
			case 's':	goto yy192;
			default:	goto yy32;
			}
yy192:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'E':
			case 'e':	goto yy193;
			default:	goto yy32;
			}
yy193:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'R':
			case 'r':	goto yy194;
			default:	goto yy32;
			}
yy194:
			++YYCURSOR;
			switch ((yych = *YYCURSOR)) {
			case '*':
			case '-':
			case '.':
			case '/':
			case '0':
			case '1':
			case '2':
			case '3':
			case '4':
			case '5':
			case '6':
			case '7':
			case '8':
			case '9':
			case '?':
			case 'A':
			case 'B':
			case 'C':
			case 'D':
			case 'E':
			case 'F':
			case 'G':
			case 'H':
			case 'I':
			case 'J':
			case 'K':
			case 'L':
			case 'M':
			case 'N':
			case 'O':
			case 'P':
			case 'Q':
			case 'R':
			case 'S':
			case 'T':
			case 'U':
			case 'V':
			case 'W':
			case 'X':
			case 'Y':
			case 'Z':
			case '_':
			case 'a':
			case 'b':
			case 'c':
			case 'd':
			case 'e':
			case 'f':
			case 'g':
			case 'h':
			case 'i':
			case 'j':
			case 'k':
			case 'l':
			case 'm':
			case 'n':
			case 'o':
			case 'p':
			case 'q':
			case 'r':
			case 's':
			case 't':
			case 'u':
			case 'v':
			case 'w':
			case 'x':
			case 'y':
			case 'z':	goto yy31;
			default:	goto yy195;
			}
yy195:
#line 196 "/Users/sweyrick/workspace/efind/src/scanner.re"
			{
                    token->tokType = TOKEN_UNARY;
                    token->opt = 3; // nouser
                    return 0;
                }
#line 3500 "/Users/sweyrick/workspace/efind/src/scanner.c"
yy196:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'O':
			case 'o':	goto yy197;
			default:	goto yy32;
			}
yy197:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'U':
			case 'u':	goto yy198;
			default:	goto yy32;
			}
yy198:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'P':
			case 'p':	goto yy199;
			default:	goto yy32;
			}
yy199:
			++YYCURSOR;
			switch ((yych = *YYCURSOR)) {
			case '*':
			case '-':
			case '.':
			case '/':
			case '0':
			case '1':
			case '2':
			case '3':
			case '4':
			case '5':
			case '6':
			case '7':
			case '8':
			case '9':
			case '?':
			case 'A':
			case 'B':
			case 'C':
			case 'D':
			case 'E':
			case 'F':
			case 'G':
			case 'H':
			case 'I':
			case 'J':
			case 'K':
			case 'L':
			case 'M':
			case 'N':
			case 'O':
			case 'P':
			case 'Q':
			case 'R':
			case 'S':
			case 'T':
			case 'U':
			case 'V':
			case 'W':
			case 'X':
			case 'Y':
			case 'Z':
			case '_':
			case 'a':
			case 'b':
			case 'c':
			case 'd':
			case 'e':
			case 'f':
			case 'g':
			case 'h':
			case 'i':
			case 'j':
			case 'k':
			case 'l':
			case 'm':
			case 'n':
			case 'o':
			case 'p':
			case 'q':
			case 'r':
			case 's':
			case 't':
			case 'u':
			case 'v':
			case 'w':
			case 'x':
			case 'y':
			case 'z':	goto yy31;
			default:	goto yy200;
			}
yy200:
#line 190 "/Users/sweyrick/workspace/efind/src/scanner.re"
			{
                    token->tokType = TOKEN_UNARY;
                    token->opt = 2; // nogroup
                    return 0;
                }
#line 3602 "/Users/sweyrick/workspace/efind/src/scanner.c"
yy201:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'S':
			case 's':	goto yy207;
			default:	goto yy159;
			}
yy202:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'R':
			case 'r':	goto yy203;
			default:	goto yy159;
			}
yy203:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'O':
			case 'o':	goto yy204;
			default:	goto yy159;
			}
yy204:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'U':
			case 'u':	goto yy205;
			default:	goto yy159;
			}
yy205:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'P':
			case 'p':	goto yy206;
			default:	goto yy159;
			}
yy206:
			yych = *++YYCURSOR;
			goto yy200;
yy207:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'E':
			case 'e':	goto yy208;
			default:	goto yy159;
			}
yy208:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'R':
			case 'r':	goto yy209;
			default:	goto yy159;
			}
yy209:
			yych = *++YYCURSOR;
			goto yy195;
yy210:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'E':
			case 'e':	goto yy211;
			default:	goto yy32;
			}
yy211:
			++YYCURSOR;
			yych = *YYCURSOR;
			switch (yych) {
			case '*':
			case '-':
			case '.':
			case '/':
			case '0':
			case '1':
			case '2':
			case '3':
			case '4':
			case '5':
			case '6':
			case '7':
			case '8':
			case '9':
			case '?':
			case 'A':
			case 'B':
			case 'C':
			case 'E':
			case 'F':
			case 'G':
			case 'H':
			case 'I':
			case 'J':
			case 'K':
			case 'L':
			case 'M':
			case 'N':
			case 'O':
			case 'P':
			case 'Q':
			case 'R':
			case 'S':
			case 'T':
			case 'U':
			case 'V':
			case 'W':
			case 'X':
			case 'Y':
			case 'Z':
			case '_':
			case 'a':
			case 'b':
			case 'c':
			case 'e':
			case 'f':
			case 'g':
			case 'h':
			case 'i':
			case 'j':
			case 'k':
			case 'l':
			case 'm':
			case 'n':
			case 'o':
			case 'p':
			case 'q':
			case 'r':
			case 's':
			case 't':
			case 'u':
			case 'v':
			case 'w':
			case 'x':
			case 'y':
			case 'z':	goto yy31;
			case 'D':
			case 'd':	goto yy211;
			default:	goto yy213;
			}
yy213:
#line 124 "/Users/sweyrick/workspace/efind/src/scanner.re"
			{
                    token->tokType = TOKEN_NAMED;
                    token->opt = 0; // name
                    return 0;
                }
#line 3746 "/Users/sweyrick/workspace/efind/src/scanner.c"
yy214:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'D':
			case 'd':	goto yy216;
			case 'Y':
			case 'y':	goto yy39;
			default:	goto yy32;
			}
yy215:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'E':
			case 'e':	goto yy39;
			default:	goto yy32;
			}
yy216:
			++YYCURSOR;
			switch ((yych = *YYCURSOR)) {
			case '*':
			case '-':
			case '.':
			case '/':
			case '0':
			case '1':
			case '2':
			case '3':
			case '4':
			case '5':
			case '6':
			case '7':
			case '8':
			case '9':
			case '?':
			case 'A':
			case 'B':
			case 'C':
			case 'D':
			case 'E':
			case 'F':
			case 'G':
			case 'H':
			case 'I':
			case 'J':
			case 'K':
			case 'L':
			case 'M':
			case 'N':
			case 'O':
			case 'P':
			case 'Q':
			case 'R':
			case 'S':
			case 'T':
			case 'U':
			case 'V':
			case 'W':
			case 'X':
			case 'Y':
			case 'Z':
			case '_':
			case 'a':
			case 'b':
			case 'c':
			case 'd':
			case 'e':
			case 'f':
			case 'g':
			case 'h':
			case 'i':
			case 'j':
			case 'k':
			case 'l':
			case 'm':
			case 'n':
			case 'o':
			case 'p':
			case 'q':
			case 'r':
			case 's':
			case 't':
			case 'u':
			case 'v':
			case 'w':
			case 'x':
			case 'y':
			case 'z':	goto yy31;
			default:	goto yy217;
			}
yy217:
#line 65 "/Users/sweyrick/workspace/efind/src/scanner.re"
			{
                    token->tokType = TOKEN_AND;
                    return 0;
                }
#line 3842 "/Users/sweyrick/workspace/efind/src/scanner.c"
yy218:
			++YYCURSOR;
			switch ((yych = *YYCURSOR)) {
			case '*':
			case '-':
			case '.':
			case '/':
			case '0':
			case '1':
			case '2':
			case '3':
			case '4':
			case '5':
			case '6':
			case '7':
			case '8':
			case '9':
			case '?':
			case 'A':
			case 'B':
			case 'C':
			case 'D':
			case 'E':
			case 'F':
			case 'G':
			case 'H':
			case 'I':
			case 'J':
			case 'K':
			case 'L':
			case 'M':
			case 'N':
			case 'O':
			case 'P':
			case 'Q':
			case 'R':
			case 'S':
			case 'T':
			case 'U':
			case 'V':
			case 'W':
			case 'X':
			case 'Y':
			case 'Z':
			case '_':
			case 'a':
			case 'b':
			case 'c':
			case 'd':
			case 'e':
			case 'f':
			case 'g':
			case 'h':
			case 'i':
			case 'j':
			case 'k':
			case 'l':
			case 'm':
			case 'n':
			case 'o':
			case 'p':
			case 'q':
			case 'r':
			case 's':
			case 't':
			case 'u':
			case 'v':
			case 'w':
			case 'x':
			case 'y':
			case 'z':	goto yy31;
			default:	goto yy219;
			}
yy219:
#line 60 "/Users/sweyrick/workspace/efind/src/scanner.re"
			{
                    token->tokType = TOKEN_OR;
                    return 0;
                }
#line 3922 "/Users/sweyrick/workspace/efind/src/scanner.c"
yy220:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'N':
			case 'n':	goto yy221;
			default:	goto yy32;
			}
yy221:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'E':
			case 'e':	goto yy222;
			default:	goto yy32;
			}
yy222:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'D':
			case 'd':	goto yy223;
			case 'R':
			case 'r':	goto yy224;
			default:	goto yy32;
			}
yy223:
			yych = *(YYMARKER = ++YYCURSOR);
			switch (yych) {
			case ' ':	goto yy226;
			default:	goto yy32;
			}
yy224:
			++YYCURSOR;
			switch ((yych = *YYCURSOR)) {
			case '*':
			case '-':
			case '.':
			case '/':
			case '0':
			case '1':
			case '2':
			case '3':
			case '4':
			case '5':
			case '6':
			case '7':
			case '8':
			case '9':
			case '?':
			case 'A':
			case 'B':
			case 'C':
			case 'D':
			case 'E':
			case 'F':
			case 'G':
			case 'H':
			case 'I':
			case 'J':
			case 'K':
			case 'L':
			case 'M':
			case 'N':
			case 'O':
			case 'P':
			case 'Q':
			case 'R':
			case 'S':
			case 'T':
			case 'U':
			case 'V':
			case 'W':
			case 'X':
			case 'Y':
			case 'Z':
			case '_':
			case 'a':
			case 'b':
			case 'c':
			case 'd':
			case 'e':
			case 'f':
			case 'g':
			case 'h':
			case 'i':
			case 'j':
			case 'k':
			case 'l':
			case 'm':
			case 'n':
			case 'o':
			case 'p':
			case 'q':
			case 'r':
			case 's':
			case 't':
			case 'u':
			case 'v':
			case 'w':
			case 'x':
			case 'y':
			case 'z':	goto yy31;
			default:	goto yy225;
			}
yy225:
#line 114 "/Users/sweyrick/workspace/efind/src/scanner.re"
			{
                    token->tokType = TOKEN_OWNEDBY;
                    return 0;
                }
#line 4031 "/Users/sweyrick/workspace/efind/src/scanner.c"
yy226:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'B':
			case 'b':	goto yy227;
			default:	goto yy159;
			}
yy227:
			yych = *++YYCURSOR;
			switch (yych) {
			case 'Y':
			case 'y':	goto yy228;
			default:	goto yy159;
			}
yy228:
			++YYCURSOR;
			yych = *YYCURSOR;
			goto yy225;
		}
#line 240 "/Users/sweyrick/workspace/efind/src/scanner.re"


	}
	return r;
}
